import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import {getDatabase,ref,get,set,push,onValue,update,remove} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';

const auth=getAuth(),db=getDatabase();
let state={code:null,room:null,channel:null,channels:{},categories:{}};
let channelUnsub=null,categoryUnsub=null,messageUnsub=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const avatar=p=>p?.avatarData||p?.avatar||null;
const $=id=>document.getElementById(id);

function cleanup(){channelUnsub?.();categoryUnsub?.();messageUnsub?.();channelUnsub=categoryUnsub=messageUnsub=null;state={code:null,room:null,channel:null,channels:{},categories:{}};document.getElementById('p2p-fixed-channel-sidebar')?.remove()}
function style(){if($('p2p-fixed-channel-style'))return;const s=document.createElement('style');s.id='p2p-fixed-channel-style';s.textContent=`
#p2p-fixed-channel-sidebar{width:250px;min-width:180px;max-width:420px;resize:horizontal;overflow:hidden;flex:none;background:var(--panel);border-right:1px solid var(--line);display:flex;flex-direction:column;height:100%;z-index:5}
#p2p-fixed-channel-sidebar .fc-head{height:60px;min-height:60px;padding:0 8px 0 14px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:5px;font-weight:800}
#p2p-fixed-channel-sidebar .fc-title{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
#p2p-fixed-channel-sidebar .fc-head button{width:34px;height:34px;border:0;background:transparent;color:var(--muted);border-radius:7px;font-size:18px;cursor:pointer}
#p2p-fixed-channel-sidebar .fc-head button:hover{background:var(--panel2);color:var(--text)}
#p2p-fixed-channel-sidebar .fc-list{padding:8px;overflow:auto;flex:1}
#p2p-fixed-channel-sidebar .fc-cat{display:flex;align-items:center;gap:5px;width:100%;border:0;background:transparent;color:var(--muted);padding:8px 5px 5px;text-align:left;font-size:11px;font-weight:800;text-transform:uppercase;cursor:pointer}
#p2p-fixed-channel-sidebar .fc-cat-items{padding-bottom:4px}
#p2p-fixed-channel-sidebar .fc-channel{display:flex;align-items:center;gap:8px;width:100%;border:0;background:transparent;color:var(--muted);padding:7px 9px;border-radius:6px;text-align:left;cursor:pointer}
#p2p-fixed-channel-sidebar .fc-channel:hover,#p2p-fixed-channel-sidebar .fc-channel.active{background:var(--panel2);color:var(--text)}
#p2p-fixed-channel-sidebar .fc-channel .hash{font-size:18px}
#p2p-fixed-channel-sidebar .fc-empty{padding:10px;color:var(--muted);font-size:12px}
.fc-context{position:fixed;z-index:100000;background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:5px;box-shadow:0 8px 25px #0006}
.fc-context button{display:block;width:180px;border:0;background:transparent;color:var(--text);padding:9px;text-align:left;border-radius:5px;cursor:pointer}.fc-context button:hover{background:var(--panel2)}
.fc-messages{flex:1;overflow:auto;padding:20px}.fc-message{display:flex;gap:10px;padding:8px 6px;border-radius:7px}.fc-message:hover{background:var(--panel2)}.fc-avatar{width:38px;height:38px;min-width:38px;height:38px;border-radius:50%;object-fit:cover;background:var(--panel2);display:grid;place-items:center;overflow:hidden}.fc-avatar img{width:100%;height:100%;object-fit:cover}.fc-body{min-width:0;flex:1}.fc-body b{display:block}.fc-body small{display:block;color:var(--muted)}.fc-body p{margin:2px 0;white-space:pre-wrap;overflow-wrap:anywhere}.fc-composer{padding:15px 20px;border-top:1px solid var(--line);display:flex;gap:8px}.fc-composer textarea{flex:1;resize:none;background:var(--input);border:1px solid var(--line);color:var(--text);border-radius:9px;padding:12px;outline:none}.fc-composer button{border:0;background:var(--accent);color:#fff;border-radius:9px;padding:0 20px;font-weight:700;cursor:pointer}.fc-composer .fc-tool{width:42px;padding:0;background:transparent;color:var(--muted);font-size:20px}.fc-composer .fc-tool:hover{background:var(--panel2);color:var(--text)}
.fc-invite-row{display:flex;align-items:center;gap:10px;padding:9px;background:var(--panel2);border-radius:8px;margin-top:6px}.fc-invite-row>div{flex:1;min-width:0}.fc-invite-row small{display:block;color:var(--muted)}
`;document.head.appendChild(s)}
function panel(){let p=$('p2p-fixed-channel-sidebar');if(!p){p=document.createElement('aside');p.id='p2p-fixed-channel-sidebar';const main=document.querySelector('.main');if(main?.parentElement)main.parentElement.insertBefore(p,main)}return p}
function context(e,items){e.preventDefault();document.querySelector('.fc-context')?.remove();const m=document.createElement('div');m.className='fc-context';m.style.left=Math.min(e.clientX,innerWidth-195)+'px';m.style.top=Math.min(e.clientY,innerHeight-180)+'px';items.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{m.remove();fn()};m.appendChild(b)});document.body.appendChild(m);setTimeout(()=>document.addEventListener('click',()=>m.remove(),{once:true}),0)}
function render(){if(!state.code)return;const p=panel(),cats=state.categories,channels=state.channels;const grouped={};Object.keys(cats).forEach(id=>grouped[id]=[]);const unc=[];Object.entries(channels).forEach(([id,ch])=>(ch.category&&grouped[ch.category]?grouped[ch.category]:unc).push([id,ch]));const cat=(id,c)=>`<button class="fc-cat" data-fc-cat="${esc(id)}"><span>▾</span><span>${esc(c.name||'Category')}</span></button><div class="fc-cat-items" data-fc-items="${esc(id)}">${grouped[id].map(channelHTML).join('')}</div>`;p.innerHTML=`<div class="fc-head"><span class="fc-title" title="${esc(state.room?.name||'Group')}">${esc(state.room?.name||'Group')}</span><button id="fc-invite" title="Invite friends" type="button">➕</button><button id="fc-settings" title="Group settings" type="button">⚙</button></div><div class="fc-list">${Object.entries(cats).map(([id,c])=>cat(id,c)).join('')}${unc.map(channelHTML).join('')}${!Object.keys(channels).length?'<div class="fc-empty">No channels yet.</div>':''}</div>`;p.querySelector('#fc-invite').onclick=invite;p.querySelector('#fc-settings').onclick=settings;p.querySelectorAll('[data-fc-channel]').forEach(b=>{b.onclick=()=>select(b.dataset.fcChannel);b.oncontextmenu=e=>context(e,[['Edit channel',()=>editChannel(b.dataset.fcChannel)],['Delete channel',()=>deleteChannel(b.dataset.fcChannel)]]);});p.querySelectorAll('[data-fc-cat]').forEach(b=>{b.onclick=()=>{const items=p.querySelector(`[data-fc-items="${CSS.escape(b.dataset.fcCat)}"]`);if(items){items.hidden=!items.hidden;b.firstElementChild.textContent=items.hidden?'▸':'▾'}};b.oncontextmenu=e=>context(e,[['Edit category',()=>editCategory(b.dataset.fcCat)],['Delete category',()=>deleteCategory(b.dataset.fcCat)]]);});p.oncontextmenu=e=>{if(e.target.closest('[data-fc-channel],[data-fc-cat]'))return;context(e,[['New Channel',createChannel],['New Category',createCategory]])}}
function channelHTML([id,ch]){return `<button class="fc-channel${state.channel===id?' active':''}" data-fc-channel="${esc(id)}"><span class="hash">#</span><span>${esc(ch.name||id)}</span></button>`}
async function load(code){const s=await get(ref(db,`rooms/${code}`));if(!s.exists())return;channelUnsub?.();categoryUnsub?.();messageUnsub?.();const data=s.val()||{};state={code,room:data.meta||{},channel:null,channels:{},categories:{}};const g=await get(ref(db,`rooms/${code}/channels/general`));if(!g.exists())await set(ref(db,`rooms/${code}/channels/general`),{name:'general',createdBy:state.room.owner,createdAt:Date.now()});channelUnsub=onValue(ref(db,`rooms/${code}/channels`),s=>{state.channels=s.val()||{};render()});categoryUnsub=onValue(ref(db,`rooms/${code}/categories`),s=>{state.categories=s.val()||{};render()});const [cs,gs]=await Promise.all([get(ref(db,`rooms/${code}/channels`)),get(ref(db,`rooms/${code}/categories`))]);state.channels=cs.val()||{};state.categories=gs.val()||{};render();const first=Object.keys(state.channels).sort((a,b)=>(state.channels[a]?.createdAt||0)-(state.channels[b]?.createdAt||0))[0]||'general';await select(first)}
async function select(id){if(!state.code)return;state.channel=id;const ch=state.channels[id]||{name:id};$('view-title').textContent=`# ${ch.name||id}`;$('view-sub').textContent=state.room?.name||'Group';$('header-actions').innerHTML='';$('content').innerHTML=`<div id="fc-messages" class="fc-messages"></div><div class="fc-composer"><button type="button" id="fc-file" class="fc-tool" title="Add image or GIF">＋</button><input id="fc-file-input" type="file" accept="image/*,.gif,image/gif" hidden><textarea id="fc-input" placeholder="Message #${esc(ch.name||id)}..."></textarea><button type="button" id="fc-emoji" class="fc-tool" title="Emoji">☺</button><button id="fc-send" type="button">Send</button></div>`;render();messageUnsub?.();const path=ref(db,`rooms/${state.code}/channels/${id}/messages`);const messages=$('fc-messages');messageUnsub=onValue(path,s=>{if(state.channel!==id)return;const x=s.val()||{};messages.innerHTML=Object.entries(x).sort((a,b)=>(a[1]?.time||0)-(b[1]?.time||0)).map(([mid,v])=>{const pic=v.avatar||null;return `<div class="fc-message" data-message-id="${esc(mid)}"><div class="fc-avatar">${pic?`<img src="${esc(pic)}" alt="">`:esc((v.name||'U').trim().charAt(0).toUpperCase()||'U')}</div><div class="fc-body"><b>${esc(v.name||'User')}</b><small>${new Date(v.time||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small><p>${esc(v.text||'')}</p></div></div>`}).join('');messages.scrollTop=messages.scrollHeight});const send=async()=>{const i=$('fc-input'),text=i?.value.trim();if(!text||state.channel!==id)return;const p=(await get(ref(db,`users/${auth.currentUser.uid}/profile`))).val()||{};await push(path,{uid:auth.currentUser.uid,name:p.username||auth.currentUser.displayName||'User',avatar:avatar(p),text,time:Date.now()});i.value='';i.focus()};$('fc-send').onclick=send;
const emoji=$('fc-emoji'),input=$('fc-input'),fileBtn=$('fc-file'),fileInput=$('fc-file-input');
emoji.onclick=()=>window.P2PEmoji?.picker?.(emoji,e=>{input.value+=e;input.focus()});
fileBtn.onclick=()=>fileInput.click();
fileInput.onchange=()=>{const file=fileInput.files?.[0];fileInput.value='';if(!file)return;if(!file.type.startsWith('image/'))return alert('Please choose an image or GIF.');if(file.size>10*1024*1024)return alert('Images and GIFs must be 10 MB or smaller.');const reader=new FileReader();reader.onload=()=>{input.value='[P2P_IMAGE]'+reader.result;send()};reader.readAsDataURL(file)};
$('fc-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}
async function createChannel(){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can create channels.');const name=prompt('Channel name:','new-channel')?.trim().toLowerCase().replace(/[^a-z0-9-_ ]/g,'').replace(/\s+/g,'-').slice(0,40);if(name)await set(ref(db,`rooms/${state.code}/channels/${name}`),{name,createdBy:auth.currentUser.uid,createdAt:Date.now()})}
async function createCategory(){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can create categories.');const name=prompt('Category name:','Category')?.trim().slice(0,40);if(name)await push(ref(db,`rooms/${state.code}/categories`),{name,createdBy:auth.currentUser.uid,createdAt:Date.now()})}
async function editChannel(id){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can edit channels.');const ch=state.channels[id]||{};const name=prompt('Channel name:',ch.name||id)?.trim();if(name)await update(ref(db,`rooms/${state.code}/channels/${id}`),{name})}
async function deleteChannel(id){if(id==='general')return alert('The general channel cannot be deleted.');if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can delete channels.');if(confirm(`Delete #${state.channels[id]?.name||id}?`))await remove(ref(db,`rooms/${state.code}/channels/${id}`))}
async function editCategory(id){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can edit categories.');const name=prompt('Category name:',state.categories[id]?.name||'Category')?.trim();if(name)await update(ref(db,`rooms/${state.code}/categories/${id}`),{name})}
async function deleteCategory(id){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can delete categories.');if(!confirm(`Delete category ${state.categories[id]?.name||'this category'}?`))return;const changes={};Object.entries(state.channels).forEach(([cid,ch])=>{if(ch.category===id)changes[`rooms/${state.code}/channels/${cid}/category`]=null});if(Object.keys(changes).length)await update(ref(db),changes);await remove(ref(db,`rooms/${state.code}/categories/${id}`))}
async function settings(){if(state.room?.owner!==auth.currentUser?.uid)return alert('Only the group owner can open group settings.');const name=prompt('Group name:',state.room.name||'')?.trim();if(name){await update(ref(db,`rooms/${state.code}/meta`),{name});state.room.name=name;render()}}
async function invite(){const friends=(await get(ref(db,`users/${auth.currentUser.uid}/friends`))).val()||{};const m=document.createElement('div');m.className='modal-bg';m.innerHTML=`<div class="modal"><button class="x" id="fc-ix">×</button><h2>Invite friends</h2><p class="muted">Invite a friend to ${esc(state.room?.name||state.code)}.</p><div>${Object.entries(friends).length?Object.entries(friends).map(([id,f])=>`<div class="fc-invite-row"><div><b>${esc(f.username||id)}</b><small>${esc(f.status||'')}</small></div><button data-fc-invite="${esc(id)}">Invite</button></div>`).join(''):'<p class="muted">You have no friends yet.</p>'}</div></div>`;$('modal-root').appendChild(m);m.querySelector('#fc-ix').onclick=()=>m.remove();m.querySelectorAll('[data-fc-invite]').forEach(b=>b.onclick=async()=>{await push(ref(db,`users/${b.dataset.fcInvite}/groupInvites`),{roomCode:state.code,roomName:state.room?.name||state.code,fromUid:auth.currentUser.uid,fromName:auth.currentUser.displayName||'User',createdAt:Date.now()});b.textContent='Invited';b.disabled=true})}
function home(){cleanup();$('view-title').textContent='Welcome';$('view-sub').textContent='Private conversations and rooms';$('header-actions').innerHTML=''}
function hook(){style();document.addEventListener('click',e=>{const room=e.target.closest('#room-list [data-room]');if(room){e.preventDefault();e.stopImmediatePropagation();load(room.dataset.room)}},true);$('p2p-home')?.addEventListener('click',home,true);onAuthStateChanged(auth,u=>{if(!u){cleanup();return}})}
hook();