import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,onValue,get,set,remove,update}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';const auth=getAuth(),db=getDatabase(),meProfile=async uid=>(await get(ref(db,`users/${uid}/profile`))).val()||{};let me=null,friendUid=null,friendName='Friend',toneTimer=null,audioCtx=null,osc=null,callUnsub=null,incoming=new Set(),callToken=0,inactivityTimer=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function tone(on){if(on){if(osc)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();osc=audioCtx.createOscillator();const g=audioCtx.createGain();g.gain.value=.035;osc.connect(g).connect(audioCtx.destination);osc.start();let high=false;toneTimer=setInterval(()=>{if(!osc)return;high=!high;osc.frequency.setValueAtTime(high?880:660,audioCtx.currentTime)},700)}catch{}}else{clearInterval(toneTimer);toneTimer=null;try{osc?.stop()}catch{}osc=null;try{audioCtx?.close()}catch{}audioCtx=null}}
function remember(){document.querySelectorAll('#dm-list [data-dm]').forEach(b=>{if(b.dataset.callBound)return;b.dataset.callBound='1';b.addEventListener('click',()=>{friendUid=b.dataset.dm;friendName=b.textContent.trim()||'Friend';setTimeout(button,0)},{capture:true})})}
function button(){const a=document.getElementById('header-actions'),sub=document.getElementById('view-sub');if(!a||!friendUid||!sub?.textContent.includes('Private conversation'))return;if(a.querySelector('#p2p-call'))return;const b=document.createElement('button');b.id='p2p-call';b.type='button';b.className='p2p-call-button';b.title='Start voice call';b.setAttribute('aria-label','Start voice call');b.textContent='☎';b.onclick=e=>{e.preventDefault();e.stopPropagation();start(friendUid,friendName)};a.prepend(b)}
function participant(name,p,extra=''){const image=p?.avatarData||p?.avatar;return `<div class="p2p-call-participant ${extra}"><div class="p2p-call-avatar-wrap"><div class="p2p-inline-call-avatar">${image?`<img src="${esc(image)}" alt="">`:esc((name||'U')[0].toUpperCase())}</div></div><div class="p2p-inline-call-name">${esc(name||'User')}</div></div>`}
async function fillAvatars(d,uid,name,localUid){try{const remote=await meProfile(uid),local=await meProfile(localUid);const rp=d.querySelector('.remote .p2p-inline-call-avatar'),lp=d.querySelector('.local .p2p-inline-call-avatar');const rimg=remote.avatarData||remote.avatar,limg=local.avatarData||local.avatar;if(rimg&&rp)rp.innerHTML=`<img src="${esc(rimg)}" alt="">`;if(limg&&lp)lp.innerHTML=`<img src="${esc(limg)}" alt="">`}catch{}}
function hookActivity(){window.P2PVoice?.setActivityCallbacks?.(v=>document.querySelector('.p2p-inline-call .local')?.classList.toggle('speaking',v),v=>document.querySelector('.p2p-inline-call .remote')?.classList.toggle('speaking',v))}
function callPanel(mode,name,uid){document.querySelector('.p2p-inline-call')?.remove();const host=document.getElementById('content');if(!host)return null;const ownName=me?.displayName||'You';const d=document.createElement('div');d.className=`p2p-inline-call p2p-call-${mode}`;let people=mode==='calling'?participant(name,{},'remote faded')+participant(ownName,{},'local centered'):participant(name,{},'remote')+participant(ownName,{},'local');d.innerHTML=`<div class="p2p-call-participants">${people}</div><div class="p2p-inline-call-state">${mode==='incoming'?'Incoming voice call':mode==='calling'?'Calling…':'Voice connected'}</div><div class="p2p-inline-call-actions">${mode==='incoming'?'<button class="p2p-call-answer" id="p2p-call-answer">Answer</button><button class="p2p-call-decline" id="p2p-call-decline">Decline</button>':'<button class="p2p-call-end" id="p2p-call-end">End call</button>'}</div>`;host.prepend(d);fillAvatars(d,uid,name,me?.uid);hookActivity();return d}
function cleanupCall(){clearTimeout(inactivityTimer);inactivityTimer=null;callUnsub?.();callUnsub=null;tone(false);document.querySelector('.p2p-inline-call')?.remove();window.P2PVoice?.setActivityCallbacks?.(null,null);window.P2PVoice?.leave?.()}
async function finish(dm){const token=callToken;try{const c=(await get(ref(db,`dms/${dm}/call`))).val();if(c&&(!c.to||c.to===me?.uid||c.from===me?.uid))await remove(ref(db,`dms/${dm}/call`))}finally{if(token===callToken)cleanupCall()}}
function armInactivity(dm){clearTimeout(inactivityTimer);inactivityTimer=setTimeout(async()=>{const c=(await get(ref(db,`dms/${dm}/call`))).val();if(c?.state==='accepted'&&c.lastActivity<Date.now()-180000){await remove(ref(db,`dms/${dm}/call`));cleanupCall()}},180000)}
async function start(uid,name){if(!me||!uid)return;cleanupCall();callToken++;const token=callToken;friendUid=uid;friendName=name||'Friend';const dm=[me.uid,uid].sort().join('_'),callRef=ref(db,`dms/${dm}/call`);tone(true);const d=callPanel('calling',friendName,uid);if(!d)return;try{await window.P2PVoice?.startDMCall?.(uid,friendName)}catch(e){console.error('[Peer2Peer call offer]',e);tone(false);d.querySelector('.p2p-inline-call-state').textContent='Could not start voice call';return}await set(callRef,{from:me.uid,to:uid,name:me.displayName||'User',targetName:friendName,state:'ringing',time:Date.now(),lastActivity:Date.now()});callUnsub=onValue(callRef,cSnap=>{if(token!==callToken)return;const c=cSnap.val();if(!c){cleanupCall();return}if(c.state==='accepted'){tone(false);const live=callPanel('connected',friendName,uid);hookActivity();live?.querySelector('#p2p-call-end')?.addEventListener('click',()=>finish(dm));armInactivity(dm)}else if(['declined','cancelled','timeout','ended'].includes(c.state)){cleanupCall()}});d.querySelector('#p2p-call-end').onclick=()=>finish(dm);setTimeout(async()=>{if(token!==callToken)return;const c=(await get(callRef)).val();if(c?.state==='ringing'){await remove(callRef);cleanupCall()}},30000)}
function watchIncoming(){if(!me)return;onValue(ref(db,'dms'),snap=>{for(const[dm,data]of Object.entries(snap.val()||{})){const c=data?.call;if(!c||c.to!==me.uid||c.state!=='ringing'||c.time<Date.now()-30000||incoming.has(dm))continue;incoming.add(dm);friendUid=c.from;friendName=c.name||'Friend';const d=callPanel('incoming',friendName,c.from);if(!d){incoming.delete(dm);continue}tone(true);d.querySelector('#p2p-call-answer').onclick=async()=>{tone(false);try{const peer=await window.P2PVoice?.answerDMCall?.(c.from);if(!peer)throw Error('No WebRTC offer found');await update(ref(db,`dms/${dm}/call`),{state:'accepted',by:me.uid,lastActivity:Date.now()});incoming.delete(dm);const live=callPanel('connected',c.name,c.from);hookActivity();live?.querySelector('#p2p-call-end')?.addEventListener('click',()=>finish(dm));armInactivity(dm)}catch(e){console.error('[Peer2Peer call answer]',e);await remove(ref(db,`dms/${dm}/call`));incoming.delete(dm);cleanupCall()}};d.querySelector('#p2p-call-decline').onclick=async()=>{incoming.delete(dm);tone(false);await remove(ref(db,`dms/${dm}/call`));d.remove()}}})}
new MutationObserver(()=>{remember();button()}).observe(document.body,{childList:true,subtree:true});remember();onAuthStateChanged(auth,u=>{me=u;if(u)watchIncoming()});window.P2PCallUI={start};