import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,onValue,get,set,remove}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';const auth=getAuth(),db=getDatabase();let me=null,friendUid=null,friendName='Friend',toneTimer=null,audioCtx=null,osc=null,callUnsub=null,incoming=new Set(),callToken=0;const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function tone(on){if(on){if(osc)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();osc=audioCtx.createOscillator();const g=audioCtx.createGain();g.gain.value=.035;osc.connect(g).connect(audioCtx.destination);osc.start();let high=false;toneTimer=setInterval(()=>{if(!osc)return;high=!high;osc.frequency.setValueAtTime(high?880:660,audioCtx.currentTime)},700)}catch{}}else{clearInterval(toneTimer);toneTimer=null;try{osc?.stop()}catch{}osc=null;try{audioCtx?.close()}catch{}audioCtx=null}}
function remember(){document.querySelectorAll('#dm-list [data-dm]').forEach(b=>{if(b.dataset.callBound)return;b.dataset.callBound='1';b.addEventListener('click',()=>{friendUid=b.dataset.dm;friendName=b.textContent.trim()||'Friend'},{capture:true})})}
function button(){const a=document.getElementById('header-actions'),sub=document.getElementById('view-sub');if(!a||!friendUid||a.querySelector('#p2p-call')||!sub?.textContent.includes('Private conversation'))return;const b=document.createElement('button');b.id='p2p-call';b.type='button';b.className='p2p-call-button';b.title='Start voice call';b.setAttribute('aria-label','Start voice call');b.textContent='☎';b.onclick=e=>{e.preventDefault();e.stopPropagation();start(friendUid,friendName)};a.prepend(b)}
async function avatarFor(uid){try{const p=(await get(ref(db,`users/${uid}/profile`))).val()||{};return p.avatarData||p.avatar||''}catch{return''}}
async function screen(mode,name,uid){document.getElementById('p2p-call-screen')?.remove();const av=await avatarFor(uid),d=document.createElement('div');d.id='p2p-call-screen';d.className='p2p-call-screen';d.innerHTML=`<div class="p2p-call-card">${av?`<img class="p2p-call-avatar-img" src="${esc(av)}" alt="">`:`<div class="p2p-call-avatar">${esc((name||'U')[0].toUpperCase())}</div>`}<div class="p2p-call-name">${esc(name||'User')}</div><div class="p2p-call-state">${mode==='incoming'?'Incoming voice call':mode==='calling'?'Calling…':'Voice connected'}</div><div class="p2p-call-actions">${mode==='incoming'?'<button class="p2p-call-answer" id="p2p-call-answer">Answer</button><button class="p2p-call-decline" id="p2p-call-decline">Decline</button>':'<button class="p2p-call-end" id="p2p-call-end">End call</button>'}</div></div>`;document.body.append(d);return d}
function cleanupCall(){callUnsub?.();callUnsub=null;tone(false);document.getElementById('p2p-call-screen')?.remove();window.P2PVoice?.leave?.()}
async function finish(dm,state){const token=callToken;try{const c=(await get(ref(db,`dms/${dm}/call`))).val();if(c&&(!c.to||c.to===me?.uid||c.from===me?.uid))await remove(ref(db,`dms/${dm}/call`))}finally{if(token===callToken)cleanupCall()}}
async function start(uid,name){if(!me||!uid)return;cleanupCall();callToken++;const token=callToken;friendUid=uid;friendName=name||'Friend';const dm=[me.uid,uid].sort().join('_'),callRef=ref(db,`dms/${dm}/call`);tone(true);const d=await screen('calling',friendName,uid);await set(callRef,{from:me.uid,to:uid,name:me.displayName||'User',targetName:friendName,state:'ringing',time:Date.now()});callUnsub=onValue(callRef,cSnap=>{if(token!==callToken)return;const c=cSnap.val();if(!c){cleanupCall();return}if(c.state==='accepted'){cleanupCall();window.P2PVoice?.startDMCall?.(uid,friendName).then(async()=>{if(token!==callToken)return;const live=await screen('connected',friendName,uid);live.querySelector('#p2p-call-end').onclick=()=>finish(dm,'ended')}).catch(()=>finish(dm,'ended'))}else if(['declined','cancelled','timeout','ended'].includes(c.state)){cleanupCall()}});d.querySelector('#p2p-call-end').onclick=()=>finish(dm,'cancelled');setTimeout(async()=>{if(token!==callToken)return;const c=(await get(callRef)).val();if(c?.state==='ringing')await remove(callRef)},30000)}
function watchIncoming(){if(!me)return;onValue(ref(db,'dms'),snap=>{for(const[dm,data]of Object.entries(snap.val()||{})){const c=data?.call;if(!c||c.to!==me.uid||c.state!=='ringing'||c.time<Date.now()-30000||incoming.has(dm))continue;if(document.getElementById('p2p-call-screen'))continue;incoming.add(dm);screen('incoming',c.name,c.from).then(d=>{if(!d.isConnected){incoming.delete(dm);return}tone(true);d.querySelector('#p2p-call-answer').onclick=async()=>{tone(false);await set(ref(db,`dms/${dm}/call`),{...c,state:'accepted',by:me.uid,time:Date.now()});incoming.delete(dm);friendUid=c.from;friendName=c.name;await window.P2PVoice?.startDMCall?.(c.from,c.name);const live=await screen('connected',c.name,c.from);live.querySelector('#p2p-call-end').onclick=()=>finish(dm,'ended')};d.querySelector('#p2p-call-decline').onclick=async()=>{incoming.delete(dm);tone(false);await remove(ref(db,`dms/${dm}/call`));d.remove()}}).catch(()=>incoming.delete(dm))}})}
new MutationObserver(()=>{remember();button()}).observe(document.body,{childList:true,subtree:true});remember();onAuthStateChanged(auth,u=>{me=u;if(u)watchIncoming()});window.P2PCallUI={start};