import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,set,get,onValue,remove,onDisconnect,push}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
const auth=getAuth(),db=getDatabase();let me=null,state=null,stream=null,muted=false,deafened=false,peers=new Map(),remoteAudio=new Map(),presenceOff=null,signalOff=new Map(),activityCtx=new Map(),heartbeat=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const ice={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
function path(){return state?`rooms/${state.room}/voice/${state.channel}`:''}function pair(a,b){return[a,b].sort().join('__')}
async function profile(uid){return(await get(ref(db,`users/${uid}/profile`))).val()||{username:'Deleted User'}}
async function local(){if(stream?.active)return stream;if(!navigator.mediaDevices?.getUserMedia)throw Error('Your browser does not support microphone access.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});return stream}
function cleanupPeer(uid){peers.get(uid)?.close();peers.delete(uid);remoteAudio.get(uid)?.remove();remoteAudio.delete(uid);activityCtx.get(uid)?.close?.().catch(()=>{});activityCtx.delete(uid)}
function attachAudio(uid,s){if(remoteAudio.has(uid))return;const a=document.createElement('audio');a.autoplay=true;a.playsInline=true;a.dataset.groupVoice=uid;a.srcObject=s;a.muted=deafened;document.body.append(a);remoteAudio.set(uid,a);a.play().catch(()=>{});watchSpeaking(uid,s,false)}
function watchSpeaking(uid,s,isLocal){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),src=ctx.createMediaStreamSource(s),an=ctx.createAnalyser(),data=new Uint8Array(an.fftSize);an.fftSize=256;src.connect(an);activityCtx.set(uid,ctx);let was=false;const loop=()=>{if(!state)return;an.getByteTimeDomainData(data);let sum=0;for(const x of data){const n=(x-128)/128;sum+=n*n}const talking=Math.sqrt(sum/data.length)>.035;if(talking!==was){was=talking;const el=document.querySelector(`[data-gv-user="${CSS.escape(uid)}"]`);el?.classList.toggle('speaking',talking)}requestAnimationFrame(loop)};loop()}catch{}}
async function signal(uid,type,payload){await push(ref(db,`${path()}/signals/${pair(me.uid,uid)}`),{from:me.uid,to:uid,type,payload,time:Date.now()})}
async function connect(uid,initiator){if(uid===me.uid||peers.has(uid)||!state)return;await local();const pc=new RTCPeerConnection(ice);peers.set(uid,pc);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>attachAudio(uid,e.streams[0]);pc.onicecandidate=e=>{if(e.candidate)signal(uid,'candidate',e.candidate.toJSON())};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))cleanupPeer(uid)};if(initiator){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal(uid,'offer',{type:offer.type,sdp:offer.sdp})}}
async function handleSignal(key,v){if(!state||v.to!==me.uid)return;const uid=v.from;if(v.type==='offer'){await connect(uid,false);const pc=peers.get(uid);await pc.setRemoteDescription(v.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal(uid,'answer',{type:answer.type,sdp:answer.sdp})}else if(v.type==='answer'){const pc=peers.get(uid);if(pc&&pc.signalingState==='have-local-offer')await pc.setRemoteDescription(v.payload)}else if(v.type==='candidate'){const pc=peers.get(uid);if(pc)await pc.addIceCandidate(v.payload).catch(()=>{})}await remove(ref(db,`${path()}/signals/${pair(me.uid,uid)}/${key}`))}
function render(members){const existing=document.getElementById('p2p-group-voice');if(existing)existing.remove();const box=document.createElement('div');box.id='p2p-group-voice';box.className='p2p-group-voice';box.innerHTML=`<div class="gv-head"><div><b>Voice Connected</b><small>${esc(state?.name||'Voice channel')}</small></div><button id="gv-close" title="Disconnect">×</button></div><div class="gv-members">${Object.entries(members||{}).map(([id,u])=>`<div class="gv-member" data-gv-user="${esc(id)}"><div class="gv-avatar">${u.avatarData||u.avatar?`<img src="${esc(u.avatarData||u.avatar)}">`:esc((u.username||'U')[0])}</div><span>${esc(u.username||'Deleted User')}</span><span class="gv-state">${u.muted?'🔇':''}${u.deafened?' 🎧':''}</span></div>`).join('')}</div><div class="gv-actions"><button id="gv-mute">${muted?'Unmute':'Mute'}</button><button id="gv-deafen">${deafened?'Undeafen':'Deafen'}</button><button id="gv-leave">Disconnect</button></div>`;document.body.append(box);box.querySelector('#gv-close').onclick=leave;box.querySelector('#gv-leave').onclick=leave;box.querySelector('#gv-mute').onclick=async()=>{muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);await set(ref(db,`${path()}/members/${me.uid}/muted`),muted)};box.querySelector('#gv-deafen').onclick=async()=>{deafened=!deafened;remoteAudio.forEach(a=>a.muted=deafened);await set(ref(db,`${path()}/members/${me.uid}/deafened`),deafened)}}
export async function joinGroupVoice(room,channel,name){if(state?.room===room&&state?.channel===channel)return;await leave();await local();state={room,channel,name};const p=await profile(me.uid),base=path(),memberRef=ref(db,`${base}/members/${me.uid}`);await set(memberRef,{uid:me.uid,username:p.username||me.displayName||'User',avatarData:p.avatarData||p.avatar||null,muted:false,deafened:false,joinedAt:Date.now()});onDisconnect(memberRef).remove();heartbeat=setInterval(()=>set(ref(db,`${base}/members/${me.uid}/lastSeen`),Date.now()),15000);watchSpeaking(me.uid,stream,true);presenceOff=onValue(ref(db,`${base}/members`),async s=>{const members=s.val()||{};render(members);for(const uid of Object.keys(members)){if(uid!==me.uid&&!peers.has(uid)&&me.uid<uid)connect(uid,true)}for(const uid of [...peers.keys()])if(!members[uid])cleanupPeer(uid)});const sigRef=ref(db,`${base}/signals`);const off=onValue(sigRef,s=>{for(const [pairId,items]of Object.entries(s.val()||{})){if(!pairId.includes(me.uid))continue;for(const [k,v]of Object.entries(items||{}))handleSignal(k,v)}});signalOff.set('all',off);return true}
export async function leave(){const old=state;if(!old)return;presenceOff?.();presenceOff=null;signalOff.forEach(x=>x?.());signalOff.clear();clearInterval(heartbeat);heartbeat=null;for(const uid of [...peers.keys()])cleanupPeer(uid);activityCtx.forEach(c=>c.close?.().catch(()=>{}));activityCtx.clear();stream?.getTracks().forEach(t=>t.stop());stream=null;document.getElementById('p2p-group-voice')?.remove();state=null;muted=false;deafened=false;if(old&&me)await remove(ref(db,`rooms/${old.room}/voice/${old.channel}/members/${me.uid}`)).catch(()=>{})}
window.P2PGroupVoice={join:joinGroupVoice,leave};window.addEventListener('beforeunload',()=>{if(state&&me)remove(ref(db,`rooms/${state.room}/voice/${state.channel}/members/${me.uid}`))});onAuthStateChanged(auth,u=>{me=u;if(!u)leave()});