import {getDatabase,ref,push,set,get,update,remove} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
const db=getDatabase(),auth=getAuth();
const MOD_EMAIL='prevolveyt@gmail.com';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isMod=()=>auth.currentUser?.email?.toLowerCase()===MOD_EMAIL;
async function reportUser(uid,name){if(!auth.currentUser||uid===auth.currentUser.uid)return;const reason=prompt(`Why are you reporting ${name||'this user'}?`);if(!reason?.trim())return;await push(ref(db,'reports'),{type:'user',reportedUid:uid,reportedName:name||'User',reporterUid:auth.currentUser.uid,reporterEmail:auth.currentUser.email,reason:reason.trim(),time:Date.now(),status:'open'});alert('Report submitted.')}
async function reportMessage(message){if(!auth.currentUser||!message)return;const reason=prompt('Why are you reporting this message?');if(!reason?.trim())return;await push(ref(db,'reports'),{type:'message',reportedUid:message.uid||'',reportedName:message.name||'User',message:message.text||'',reporterUid:auth.currentUser.uid,reporterEmail:auth.currentUser.email,reason:reason.trim(),time:Date.now(),status:'open'});alert('Report submitted.')}
async function getJoinedGroups(){if(!auth.currentUser)return[];const joined=await get(ref(db,`users/${auth.currentUser.uid}/joinedRooms`));const codes=Object.keys(joined.val()||{});const groups=[];await Promise.all(codes.map(async code=>{const s=await get(ref(db,`rooms/${code}/meta`));if(s.exists())groups.push({code,name:s.val()?.name||code})}));return groups.sort((a,b)=>a.name.localeCompare(b.name))}
async function deleteJoinedGroup(code,name){if(!isMod()||!code)return;if(!confirm(`Delete “${name||code}” for everyone?\n\nThis permanently removes the group, its messages, members, and channels.`))return;try{const snap=await get(ref(db,`rooms/${code}`));if(!snap.exists()){alert('That group no longer exists.');return}const room=snap.val()||{},members=Object.keys(room.members||{}),changes={};for(const uid of members)changes[`users/${uid}/joinedRooms/${code}`]=null;changes[`rooms/${code}`]=null;await update(ref(db),changes);if(window.P2PModeration?.refreshGroups)await window.P2PModeration.refreshGroups();alert('Group deleted.')}catch(e){alert(`Could not delete the group: ${e?.message||e}`)}}
async function renderGroupDeleteTool(){const box=document.getElementById('mod-group-delete');if(!box)return;box.innerHTML='<p class="muted">Loading your groups...</p>';const groups=await getJoinedGroups();box.innerHTML=groups.length?`<label>Delete a group you are in</label><div class="mod-group-delete-row"><select id="mod-group-select">${groups.map(g=>`<option value="${esc(g.code)}">${esc(g.name)}</option>`).join('')}</select><button class="danger" id="mod-delete-group">Delete group</button></div><small class="muted">Temporary admin tool. Permanently removes the selected group.</small>`:'<p class="muted">You are not currently in any groups.</p>';document.getElementById('mod-delete-group')?.addEventListener('click',async()=>{const sel=document.getElementById('mod-group-select'),g=groups.find(x=>x.code===sel?.value);if(g)await deleteJoinedGroup(g.code,g.name)})}
function board(){if(!isMod())return;const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-bg"><div class="modal moderation-board"><button class="x" id="mod-close">×</button><h2>Moderator Board</h2><div class="mod-tabs"><button data-tab="reports">Reports</button><button data-tab="users">Users</button></div><div id="mod-content">Loading...</div><div id="mod-group-delete" class="mod-group-delete"></div></div></div>`;root.querySelector('#mod-close').onclick=()=>root.innerHTML='';root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.tab));loadTab('reports');renderGroupDeleteTool()}
async function loadTab(tab){const c=document.getElementById('mod-content');if(!c)return;if(tab==='users'){const s=await get(ref(db,'userDirectory'));const users=Object.values(s.val()||{});c.innerHTML=`<input id="mod-user-search" placeholder="Search users..."><div id="mod-users">${users.map(u=>`<div class="mod-row"><div><b>${esc(u.username||'User')}</b><small>${esc(u.status||'')}</small></div><button data-profile="${esc(u.uid)}">View profile</button></div>`).join('')||'<p class="muted">No users.</p>'}</div>`;const filter=()=>{const q=document.getElementById('mod-user-search').value.toLowerCase();document.querySelectorAll('#mod-users .mod-row').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'flex':'none')};document.getElementById('mod-user-search').oninput=filter;return}const s=await get(ref(db,'reports')),reports=Object.entries(s.val()||{}).sort((a,b)=>(b[1].time||0)-(a[1].time||0));c.innerHTML=reports.length?reports.map(([id,r])=>`<div class="mod-report"><div><b>${r.type==='message'?'Message report':'User report'}</b><small>${new Date(r.time||Date.now()).toLocaleString()}</small></div><p><b>Reported:</b> ${esc(r.reportedName||r.reportedUid)}</p>${r.type==='message'?`<p><b>Message:</b> ${esc(r.message)}</p>`:''}<p><b>Reason:</b> ${esc(r.reason)}</p><p><b>Reporter:</b> ${esc(r.reporterEmail||r.reporterUid)}</p><div class="mod-actions"><button data-report-status="${esc(id)}" data-status="reviewed">Mark reviewed</button><button data-report-status="${esc(id)}" data-status="dismissed">Dismiss</button></div></div>`).join(''):'<p class="muted">No reports yet.</p>';c.querySelectorAll('[data-report-status]').forEach(b=>b.onclick=async()=>{await update(ref(db,`reports/${b.dataset.reportStatus}`),{status:b.dataset.status,reviewedBy:auth.currentUser.uid,reviewedAt:Date.now()});loadTab('reports')})}
function installAdminButton(){const bar=document.getElementById('profile-open');if(!bar||!isMod()||document.getElementById('admin-panel-button'))return;const b=document.createElement('button');b.id='admin-panel-button';b.type='button';b.title='Admin panel';b.setAttribute('aria-label','Admin panel');b.textContent='🛡';b.onclick=e=>{e.stopPropagation();board()};bar.appendChild(b)}
onAuthStateChanged(auth,()=>setTimeout(installAdminButton,250));window.P2PModeration={reportUser,reportMessage,open:board,isMod,refreshGroups:renderGroupDeleteTool};