import {getApp} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import {getDatabase,ref,get,update,onDisconnect} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
const app=getApp(),auth=getAuth(app),db=getDatabase(app);const IDLE_MS=10*60*1000;let uid=null,manualStatus='online',idleTimer=null;
const writePresence=async status=>{if(!uid)return;await update(ref(db,`users/${uid}/profile`),{presence:status});await update(ref(db,`userDirectory/${uid}`),{presence:status})};
const setupDisconnect=async()=>{if(!uid)return;await onDisconnect(ref(db,`users/${uid}/profile`)).update({presence:'offline'});await onDisconnect(ref(db,`userDirectory/${uid}`)).update({presence:'offline'})};
const resetIdle=()=>{clearTimeout(idleTimer);if(!uid||manualStatus!=='online')return;writePresence('online');idleTimer=setTimeout(()=>writePresence('idle'),IDLE_MS)};
['mousemove','mousedown','keydown','touchstart','scroll','click'].forEach(event=>window.addEventListener(event,resetIdle,{passive:true}));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')resetIdle()});
onAuthStateChanged(auth,async user=>{clearTimeout(idleTimer);uid=user?.uid||null;if(!uid)return;const snap=await get(ref(db,`users/${uid}/profile`)),profile=snap.val()||{};manualStatus=['dnd','invisible'].includes(profile.presence)?profile.presence:'online';await setupDisconnect();await writePresence(manualStatus);resetIdle()});
window.addEventListener('beforeunload',()=>clearTimeout(idleTimer));
