import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,get,set,update,remove,onValue}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';const app=getApps().length?getApp():null;if(!app)throw Error('Firebase is not initialized');const auth=getAuth(app),db=getDatabase(app);let me=null,room=null,channel=null,stream=null,muted=false,deaf=false,peers=new Map(),presenceUnsub=null,signalUnsubs=[],activityLocal=null,activityRemote=null,activityLoops=new Map(),remoteAudioCtx=null,remoteStreams=new Map(),localPeer=null,localActivityKey='local';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function ensureDock(){let d=document.querySelector('.p2p-voice-dock');if(d)return d;d=document.createElement('div');d.className='p2p-voice-dock';document.body.append(d);return d}
function renderUsers(users){let d=ensureDock(),list=d.querySelector('.p2p-voice-users');if(!list)return;list.innerHTML=Object.entries(users||{}).map(([id,u])=>`<div class="p2p-voice-user"><span class="dot"></span><span>${esc(u.username||id)}${id===me?.uid?' (you)':''}</span></div>`).join('')||'<div class="muted">Connecting…</div>'}
function showDock(name){let d=ensureDock();d.innerHTML=`<div class="p2p-voice-head">🔊 ${esc(name||'Voice')}</div><div class="p2p-voice-users"></div><div class="p2p-voice-actions"><button id="p2p-vmute">Mute</button><button id="p2p-vdeaf">Deafen</button><button class="leave" id="p2p-vleave">Leave</button></div>`;d.querySelector('#p2p-vmute').onclick=()=>{muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);d.querySelector('#p2p-vmute').textContent=muted?'Unmute':'Mute'};d.querySelector('#p2p-vdeaf').onclick=()=>{deaf=!deaf;document.querySelectorAll('audio[data-p2p-voice]').forEach(a=>a.muted=deaf);d.querySelector('#p2p-vdeaf').textContent=deaf?'Undeafen':'Deafen'};d.querySelector('#p2p-vleave').onclick=leave}
function key(a,b){return[a,b].sort().join('_')}
function activity(s,cb,keyName){if(!s||!cb)return;try{const old=activityLoops.get(keyName);if(old)cancelAnimationFrame(old);const ctx=new(window.AudioContext||window.webkitAudioContext)(),source=ctx.createMediaStreamSource(s),an=ctx.createAnalyser();an.fftSize=256;an.smoothingTimeConstant=.7;source.connect(an);const data=new Uint8Array(an.fftSize);let last=false,quiet=0;const loop=()=>{an.getByteTimeDomainData(data);let sum=0;for(const x of data){const n=(x-128)/128;sum+=n*n}const level=Math.sqrt(sum/data.length);const speaking=level>.035;if(speaking!==last){last=speaking;cb(speaking)}activityLoops.set(keyName,requestAnimationFrame(loop))};loop()}catch(e){console.warn('[Peer2Peer voice activity]',e)}}
function clearActivity(){for(const id of activityLoops.values())cancelAnimationFrame(id);activityLoops.clear();activityLocal=null;activityRemote=null}
function attachRemoteAudio(uid,s){if(!s)return;remoteStreams.set(uid,s);let a=document.querySelector(`audio[data-p2p-voice="${uid}"]`);if(!a){a=document.createElement('audio');a.autoplay=true;a.playsInline=true;a.dataset.p2pVoice=uid;document.body.append(a)}a.srcObject=s;a.muted=deaf;const play=()=>a.play().catch(()=>{});play();activity(s,v=>activityRemote?.(uid,v),`remote-${uid}`)}
function setActivityCallbacks(local,remote){activityLocal=local;activityRemote=remote;if(stream&&local)activity(stream,local,localActivityKey);for(const[uid,s]of remoteStreams)if(remote)activity(s,v=>remote(uid,v),`remote-${uid}`)}
function addTrackToPeer(pc){stream?.getTracks().forEach(t=>pc.addTrack(t,stream))}
async function getLocal(){if(stream)return stream;stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(activityLocal)activity(stream,activityLocal,localActivityKey);return stream}
function bindPeer(uid,pc){pc.ontrack=e=>{const s=e.streams?.[0]||new MediaStream([e.track]);attachRemoteAudio(uid,s)};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState)){document.querySelector(`audio[data-p2p-voice="${uid}"]`)?.remove();remoteStreams.delete(uid);const id=activityLoops.get(`remote-${uid}`);if(id)cancelAnimationFrame(id);activityLoops.delete(`remote-${uid}`)}};pc.oniceconnectionstatechange=()=>{if(pc.iceConnectionState==='failed')pc.restartIce?.()}}
function config(){return{iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]}}
async function startDMCall(uid,name){await getLocal();const k=key(me.uid,uid),signal=ref(db,`voiceDM/${k}`);if(localPeer)localPeer.close();localPeer=new RTCPeerConnection(config());addTrackToPeer(localPeer);bindPeer(uid,localPeer);localPeer.onicecandidate=e=>{if(e.candidate)set(ref(db,`voiceDM/${k}/candidate/${me.uid}/${crypto.randomUUID()}`),e.candidate.toJSON())};const snap=await get(signal);const data=snap.val()||{};if(data.answer){await localPeer.setRemoteDescription(new RTCSessionDescription(data.answer))}else{const offer=await localPeer.createOffer();await localPeer.setLocalDescription(offer);await update(signal,{offer:{type:offer.type,sdp:offer.sdp},from:me.uid,to:uid,time:Date.now()})}onValue(ref(db,`voiceDM/${k}/answer`),async s=>{const a=s.val();if(a&&localPeer?.signalingState==='have-local-offer')await localPeer.setRemoteDescription(new RTCSessionDescription(a))});onValue(ref(db,`voiceDM/${k}/candidate/${uid}`),s=>{for(const c of Object.values(s.val()||{}))localPeer?.addIceCandidate(new RTCIceCandidate(c)).catch(()=>{})});return localPeer}
async function answerDMCall(uid){await getLocal();const k=key(me.uid,uid),signal=ref(db,`voiceDM/${k}`),snap=await get(signal),data=snap.val();if(!data?.offer)return null;if(localPeer)localPeer.close();localPeer=new RTCPeerConnection(config());addTrackToPeer(localPeer);bindPeer(uid,localPeer);localPeer.onicecandidate=e=>{if(e.candidate)set(ref(db,`voiceDM/${k}/candidate/${me.uid}/${crypto.randomUUID()}`),e.candidate.toJSON())};await localPeer.setRemoteDescription(new RTCSessionDescription(data.offer));const answer=await localPeer.createAnswer();await localPeer.setLocalDescription(answer);await set(ref(db,`voiceDM/${k}/answer`),{type:answer.type,sdp:answer.sdp});onValue(ref(db,`voiceDM/${k}/candidate/${uid}`),s=>{for(const c of Object.values(s.val()||{}))localPeer?.addIceCandidate(new RTCIceCandidate(c)).catch(()=>{})});return localPeer}
function leave(){clearActivity();for(const p of peers.values())p.close?.();peers.clear();localPeer?.close();localPeer=null;remoteStreams.clear();document.querySelectorAll('audio[data-p2p-voice]').forEach(a=>a.remove());stream?.getTracks().forEach(t=>t.stop());stream=null;document.querySelector('.p2p-voice-dock')?.remove();room=null;channel=null}
window.P2PVoice={showDock,renderUsers,startDMCall,answerDMCall,leave,setActivityCallbacks};onAuthStateChanged(auth,u=>{me=u})