import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,get,set,update,remove,onValue}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';const app=getApps().length?getApp():null;if(!app)throw Error('Firebase is not initialized');const auth=getAuth(app),db=getDatabase(app);let me=null,room=null,channel=null,stream=null,muted=false,deaf=false,peers=new Map(),presenceUnsub=null,signalUnsubs=[],activityLocal=null,activityRemote=null,activityLoops=new Map(),remoteAudioCtx=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function ensureDock(){let d=document.querySelector('.p2p-voice-dock');if(d)return d;d=document.createElement('div');d.className='p2p-voice-dock';document.body.append(d);return d}
function renderUsers(users){let d=ensureDock(),list=d.querySelector('.p2p-voice-users');if(!list)return;list.innerHTML=Object.entries(users||{}).map(([id,u])=>`<div class="p2p-voice-user"><span class="dot"></span><span>${esc(u.username||id)}${id===me?.uid?' (you)':''}</span></div>`).join('')||'<div class="muted">Connecting…</div>'}
function showDock(name){let d=ensureDock();d.innerHTML=`<div class="p2p-voice-head">🔊 ${esc(name||'Voice')}</div><div class="p2p-voice-users"></div><div class="p2p-voice-actions"><button id="p2p-vmute">Mute</button><button id="p2p-vdeaf">Deafen</button><button class="leave" id="p2p-vleave">Leave</button></div>`;d.querySelector('#p2p-vmute').onclick=()=>{muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);d.querySelector('#p2p-vmute').textContent=muted?'Unmute':'Mute'};d.querySelector('#p2p-vdeaf').onclick=()=>{deaf=!deaf;document.querySelectorAll('audio[data-p2p-voice]').forEach(a=>a.muted=deaf);d.querySelector('#p2p-vdeaf').textContent=deaf?'Undeafen':'Deafen'};d.querySelector('#p2p-vleave').onclick=leave}
function key(a,b){return[a,b].sort().join('_')}
function activity(s,cb,keyName){if(!s||!cb)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),source=ctx.createMediaStreamSource(s),an=ctx.createAnalyser();an.fftSize=256;source.connect(an);const data=new Uint8Array(an.fftSize);let last=false;const loop=()=>{an.getByteTimeDomainData(data);let sum=0;for(const x of data){const n=(x-128)/128;sum+=n*n}const speaking=Math.sqrt(sum/data.length)>.045;if(speaking!==last){last=speaking;cb(speaking)}activityLoops.set(keyName,requestAnimationFrame(loop))};loop()}catch(e){console.warn('[Peer2Peer voice activity]',e)}}
function stopActivity(){for(const id of activityLoops.values())cancelAnimationFrame(id);activityLoops.clear()}
function setActivityCallbacks(local,remote){activityLocal=local;activityRemote=remote;if(stream)activity(stream,activityLocal,'local');for(const[id,pc]of peers){const a=document.querySelector(`audio[data-p2p-voice="${CSS.escape(id)}"]`);if(a?.srcObject&&activityRemote)activity(a.srcObject,activityRemote,'remote:'+id)}}
function remoteAudio(stream,id){let a=document.querySelector(`audio[data-p2p-voice="${CSS.escape(id)}"]`);if(!a){a=document.createElement('audio');a.autoplay=true;a.playsInline=true;a.dataset.p2pVoice=id;document.body.append(a)}a.srcObject=stream;a.muted=deaf;const p=a.play();if(p?.catch)p.catch(()=>{});if(activityRemote)activity(stream,activityRemote,'remote:'+id);return a}
async function createPeer(id,initiator,basePath){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});stream?.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const rs=e.streams?.[0]||new MediaStream([e.track]);remoteAudio(rs,id)};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){pc.close();peers.delete(id);document.querySelector(`audio[data-p2p-voice="${CSS.escape(id)}"]`)?.remove()}};peers.set(id,pc);if(initiator){await pc.setLocalDescription(await pc.createOffer());await waitIce(pc);await set(ref(db,`${basePath}/${id}/${me.uid}/offer`),pc.localDescription.toJSON())}return pc}
function waitIce(pc){return new Promise(r=>{if(pc.iceGatheringState==='complete')return r();const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);r()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(r,4000)})}
async function signalPeer(id,basePath){const base=ref(db,`${basePath}/${id}/${me.uid}`),s=(await get(base)).val()||{},pc=await createPeer(id,false,basePath);if(s.offer&&!pc.currentRemoteDescription){await pc.setRemoteDescription(s.offer);await pc.setLocalDescription(await pc.createAnswer());await waitIce(pc);await set(ref(db,`${basePath}/${id}/${me.uid}/answer`),pc.localDescription.toJSON())}}
function listenRoomSignals(){signalUnsubs.forEach(x=>x?.());signalUnsubs=[];const base=ref(db,`rooms/${room}/voiceSignals/${channel}/${me.uid}`);signalUnsubs.push(onValue(base,async s=>{for(const[from,data]of Object.entries(s.val()||{})){if(from===me.uid)continue;let pc=await createPeer(from,false,`rooms/${room}/voiceSignals/${channel}`);if(data.offer&&!pc.currentRemoteDescription){await pc.setRemoteDescription(data.offer);await pc.setLocalDescription(await pc.createAnswer());await waitIce(pc);await set(ref(db,`rooms/${room}/voiceSignals/${channel}/${from}/${me.uid}/answer`),pc.localDescription.toJSON())}if(data.answer&&pc.localDescription?.type==='offer'&&!pc.currentRemoteDescription)await pc.setRemoteDescription(data.answer)}}))}
async function connectRoomUsers(users){for(const id of Object.keys(users||{}))if(id!==me.uid&&me.uid<id)await createPeer(id,true,`rooms/${room}/voiceSignals/${channel}`)}
async function join(ch){if(!me||!room)return;await leave();channel=ch;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}catch{alert('Peer2Peer needs microphone permission for voice chat.');channel=null;return}await set(ref(db,`rooms/${room}/voice/${channel}/${me.uid}`),{uid:me.uid,username:me.displayName||'User',joinedAt:Date.now()});showDock('Voice');activity(stream,activityLocal,'local');presenceUnsub=onValue(ref(db,`rooms/${room}/voice/${channel}`),async s=>{const users=s.val()||{};renderUsers(users);await connectRoomUsers(users)});listenRoomSignals()}
async function startDMCall(uid,name){if(!me||!uid)return;await leave();channel='dm';const dm=key(me.uid,uid);room=null;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})}catch{alert('Peer2Peer needs microphone permission for voice chat.');channel=null;return}try{if(remoteAudioCtx?.state==='suspended')await remoteAudioCtx.resume()}catch{}const basePath=`dms/${dm}/voiceSignals`;await set(ref(db,`dms/${dm}/voice/${me.uid}`),{uid:me.uid,username:me.displayName||'User',joinedAt:Date.now(),withUid:uid});showDock(name||'Voice call');activity(stream,activityLocal,'local');presenceUnsub=onValue(ref(db,`dms/${dm}/voice`),async s=>{const users=s.val()||{};renderUsers(users);if(users[uid]){if(me.uid<uid)await createPeer(uid,true,basePath);else await signalPeer(uid,basePath)}});listenDMInvite(dm,uid,basePath)}
function listenDMInvite(dm,uid,basePath){signalUnsubs.forEach(x=>x?.());signalUnsubs=[];signalUnsubs.push(onValue(ref(db,`${basePath}/${me.uid}`),async s=>{const data=s.val()||{};const offer=data?.offer||Object.values(data)[0]?.offer;if(!offer)return;const pc=await createPeer(uid,false,basePath);if(!pc.currentRemoteDescription){await pc.setRemoteDescription(offer);await pc.setLocalDescription(await pc.createAnswer());await waitIce(pc);await set(ref(db,`${basePath}/${uid}/${me.uid}/answer`),pc.localDescription.toJSON())}}));signalUnsubs.push(onValue(ref(db,`${basePath}/${uid}/${me.uid}/answer`),async s=>{const a=s.val(),pc=peers.get(uid);if(a&&pc?.localDescription?.type==='offer'&&!pc.currentRemoteDescription)await pc.setRemoteDescription(a)}))}
async function leave(){presenceUnsub?.();signalUnsubs.forEach(x=>x?.());presenceUnsub=null;signalUnsubs=[];stopActivity();for(const pc of peers.values())pc.close();peers.clear();stream?.getTracks().forEach(t=>t.stop());stream=null;document.querySelectorAll('audio[data-p2p-voice]').forEach(x=>x.remove());if(me&&room&&channel)await remove(ref(db,`rooms/${room}/voice/${channel}/${me.uid}`));document.querySelector('.p2p-voice-dock')?.remove();room=channel=null}
function roomCode(){const title=document.querySelector('.p2p-channel-system-title')?.textContent?.trim();const b=[...document.querySelectorAll('#room-list [data-room]')].find(x=>x.textContent.trim()===title);return b?.dataset.room||null}
function injectButtons(){document.querySelectorAll('.p2p-cs-channel').forEach(b=>{if(b.querySelector('.p2p-voice-join'))return;const x=document.createElement('button');x.type='button';x.className='p2p-voice-join';x.title='Join voice';x.textContent='🔊';x.onclick=e=>{e.stopPropagation();room=roomCode();if(room)join(b.dataset.channel)};b.append(x)})}
new MutationObserver(injectButtons).observe(document.body,{childList:true,subtree:true});onAuthStateChanged(auth,u=>me=u);window.P2PVoice={join,leave,startDMCall,setActivityCallbacks};