import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,get,set,update,push,onValue,onDisconnect,remove}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
const app=getApps().length?getApp():null;if(!app)throw Error('Firebase is not initialized');const auth=getAuth(app),db=getDatabase(app);let me=null,roomCode=null,room=null,channels={},active=null,stream=null,muted=false,deafened=false,peers=new Map(),iceQueue=new Map(),unsubs=[],handled=new Set(),analysis=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
const base=()=>active?`rooms/${active.room}/voice/${active.channel}`:'';
const profile=()=>get(ref(db,`users/${me.uid}/profile`)).then(s=>s.val()||{});
function offAll(){unsubs.splice(0).forEach(f=>f?.());}
async function mic(){if(stream?.active)return stream;if(!navigator.mediaDevices?.getUserMedia||!window.isSecureContext)throw Error('Microphone access requires HTTPS.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});return stream}
function audio(uid,s){let a=document.querySelector(`audio[data-vc="${CSS.escape(uid)}"]`);if(!a){a=document.createElement('audio');a.dataset.vc=uid;a.autoplay=true;a.playsInline=true;document.body.append(a)}a.srcObject=s;a.muted=deafened;a.play().catch(()=>{});return a}
function activity(uid,s){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),src=ctx.createMediaStreamSource(s),an=ctx.createAnalyser();an.fftSize=256;an.smoothingTimeConstant=.7;src.connect(an);const data=new Uint8Array(an.fftSize);let last=false;const loop=()=>{if(!active){ctx.close().catch(()=>{});return}an.getByteTimeDomainData(data);let sum=0;for(const n of data){const x=(n-128)/128;sum+=x*x}const now=Math.sqrt(sum/data.length)>.035;if(now!==last){last=now;document.querySelector(`[data-vc-user="${CSS.escape(uid)}"]`)?.classList.toggle('speaking',now)}analysis.set(uid,requestAnimationFrame(loop))};loop()}catch{}}
function closePeer(uid){const p=peers.get(uid);p?.pc?.close();peers.delete(uid);iceQueue.delete(uid);analysis.get(uid)&&cancelAnimationFrame(analysis.get(uid));analysis.delete(uid);document.querySelector(`audio[data-vc="${CSS.escape(uid)}"]`)?.remove()}
async function send(to,type,data){if(!active)return;await push(ref(db,`${base()}/signals/${to}`),{from:me.uid,to,type,data,time:Date.now()})}
async function makePeer(uid,offerer){if(!active||uid===me.uid)return null;if(peers.has(uid))return peers.get(uid).pc;await mic();const pc=new RTCPeerConnection(pcConfig),item={pc,remote:false};peers.set(uid,item);stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const s=e.streams?.[0]||new MediaStream([e.track]);if(e.track.kind==='audio'){audio(uid,s);activity(uid,s)}};pc.onicecandidate=e=>e.candidate&&send(uid,'candidate',e.candidate.toJSON());pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')status('Connected');if(['failed','closed'].includes(pc.connectionState))closePeer(uid)};if(offerer){const o=await pc.createOffer();await pc.setLocalDescription(o);await send(uid,'offer',{type:o.type,sdp:o.sdp})}return pc}
async function signal(key,v){if(!v||v.to!==me.uid||v.from===me.uid||handled.has(key))return;handled.add(key);const uid=v.from;try{if(v.type==='offer'){const pc=await makePeer(uid,false),item=peers.get(uid);await pc.setRemoteDescription(v.data);item.remote=true;for(const c of iceQueue.get(uid)||[])await pc.addIceCandidate(c).catch(()=>{});iceQueue.delete(uid);const a=await pc.createAnswer();await pc.setLocalDescription(a);await send(uid,'answer',{type:a.type,sdp:a.sdp})}else if(v.type==='answer'){const item=peers.get(uid);if(item&&!item.remote){await item.pc.setRemoteDescription(v.data);item.remote=true;for(const c of iceQueue.get(uid)||[])await item.pc.addIceCandidate(c).catch(()=>{});iceQueue.delete(uid)}}else if(v.type==='candidate'){const c=new RTCIceCandidate(v.data),item=peers.get(uid);if(item?.remote)await item.pc.addIceCandidate(c).catch(()=>{});else{const q=iceQueue.get(uid)||[];q.push(c);iceQueue.set(uid,q)}}}finally{await remove(ref(db,`${base()}/signals/${me.uid}/${key}`)).catch(()=>{})}}
function renderMembers(m){const box=document.getElementById('vc-members');if(!box)return;const list=Object.values(m||{});box.innerHTML=list.map(u=>`<button class="vc-user${u.muted?' muted':''}" data-vc-user="${esc(u.uid)}" type="button"><span class="vc-avatar">${u.avatar?`<img src="${esc(u.avatar)}" alt="">`:esc((u.username||'U')[0].toUpperCase())}</span><span>${esc(u.username||'User')}</span>${u.muted?'<span class="vc-muted">🔇</span>':''}</button>`).join('')||'<span class="vc-empty">Nobody is connected.</span>'}
function status(t){const x=document.getElementById('vc-status');if(x)x.textContent=t}
function view(){const c=document.getElementById('content');if(!c||!active)return;c.innerHTML=`<section class="vc-room"><div class="vc-center"><div class="vc-name">🔊 ${esc(active.name)}</div><div id="vc-status" class="vc-status">Connecting…</div><div id="vc-members" class="vc-members"></div><div class="vc-controls"><button id="vc-mic" type="button" title="Mute" aria-label="Mute">🎤</button><button id="vc-mic-menu" type="button" title="Microphone settings" aria-label="Microphone settings">⌄</button><button id="vc-deafen" type="button" title="Deafen" aria-label="Deafen">🔊</button><button id="vc-leave" class="leave" type="button" title="Leave voice channel" aria-label="Leave voice channel">☎</button></div><div id="vc-pop" class="vc-pop" hidden></div></div></section>`;document.getElementById('vc-mic').onclick=toggleMute;document.getElementById('vc-deafen').onclick=toggleDeafen;document.getElementById('vc-mic-menu').onclick=micMenu;document.getElementById('vc-leave').onclick=leave}
async function toggleMute(){muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted);await update(ref(db,`${base()}/members/${me.uid}`),{muted});const b=document.getElementById('vc-mic');if(b){b.textContent=muted?'🎙️':'🎤';b.title=muted?'Unmute':'Mute';b.setAttribute('aria-label',b.title)}}
async function toggleDeafen(){deafened=!deafened;document.querySelectorAll('audio[data-vc]').forEach(a=>a.muted=deafened);await update(ref(db,`${base()}/members/${me.uid}`),{deafened});const b=document.getElementById('vc-deafen');if(b){b.textContent=deafened?'🔇':'🔊';b.title=deafened?'Undeafen':'Deafen';b.setAttribute('aria-label',b.title)}}
async function micMenu(){const p=document.getElementById('vc-pop');if(!p)return;if(!p.hidden){p.hidden=true;return}let d=[];try{d=await navigator.mediaDevices.enumerateDevices()}catch{}const inputs=d.filter(x=>x.kind==='audioinput');p.innerHTML=`<b>Microphone</b><label>Input<select id="vc-device">${inputs.map(x=>`<option value="${esc(x.deviceId)}">${esc(x.label||'Microphone')}</option>`).join('')}</select></label><label>Input volume<input id="vc-volume" type="range" min="0" max="100" value="100"></label>`;p.hidden=false;document.getElementById('vc-volume').oninput=e=>stream?.getAudioTracks().forEach(t=>t.enabled=Number(e.target.value)>0);document.getElementById('vc-device').onchange=async e=>{try{const old=stream;stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:{exact:e.target.value},echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const t=stream.getAudioTracks()[0];peers.forEach(x=>x.pc.getSenders().find(s=>s.track?.kind==='audio')?.replaceTrack(t));old?.getTracks().forEach(x=>x.stop())}catch(err){alert(err.message||'Could not change microphone.')}}}
async function join(room,channel,name){if(!me)throw Error('You must be signed in.');if(active?.room===room&&active?.channel===channel)return;await leave();active={room,channel,name};view();try{await mic();const p=await profile(),r=ref(db,`${base()}/members/${me.uid}`);await onDisconnect(r).remove();await set(r,{uid:me.uid,username:p.username||me.displayName||'User',avatar:p.avatarData||p.avatar||null,muted:false,deafened:false,joinedAt:Date.now()});const mr=ref(db,`${base()}/members`),sr=inbox();unsubs.push(onValue(mr,s=>{const m=s.val()||{};renderMembers(m);Object.keys(m).forEach(id=>{if(id!==me.uid&&me.uid<id&&!peers.has(id))makePeer(id,true).catch(console.error)});[...peers.keys()].forEach(id=>{if(!m[id])closePeer(id)})}));unsubs.push(onValue(sr,s=>{Object.entries(s.val()||{}).forEach(([k,v])=>signal(k,v))}));status('Connected');activity(me.uid,stream)}catch(e){await leave();throw e}return true}
function inbox(){return ref(db,`${base()}/signals/${me.uid}`)}
async function leave(){if(!active)return;const old=active;active=null;offAll();for(const id of [...peers.keys()])closePeer(id);analysis.forEach(x=>cancelAnimationFrame(x));analysis.clear();stream?.getTracks().forEach(t=>t.stop());stream=null;document.querySelectorAll('audio[data-vc]').forEach(a=>a.remove());document.getElementById('content')?.querySelector('.vc-room')?.remove();await remove(ref(db,`rooms/${old.room}/voice/${old.channel}/members/${me?.uid}`)).catch(()=>{});}
async function loadRoom(code){roomCode=code;const s=await get(ref(db,`rooms/${code}`));if(!s.exists())return;const d=s.val()||{};room=d.meta||{};channels=d.channels||{}}
function channelIsVoice(ch){const t=String(ch?.type||'').toLowerCase();return t==='voice'||t==='vc'||t==='voice_channel'||ch?.voice===true||ch?.kind==='voice'}
window.P2PVoiceRoom={join,leave,participantMenu:uid=>{const a=document.querySelector(`audio[data-vc="${CSS.escape(uid)}"]`);if(!a)return;const m=document.createElement('div');m.className='vc-user-menu';m.innerHTML=`<b>Participant</b><label>Local volume<input id="vc-user-vol" type="range" min="0" max="200" value="100"></label><button id="vc-user-mute" type="button">Local mute</button>`;document.body.append(m);m.querySelector('#vc-user-vol').oninput=e=>a.volume=Number(e.target.value)/100;m.querySelector('#vc-user-mute').onclick=()=>a.muted=!a.muted;setTimeout(()=>document.addEventListener('click',()=>m.remove(),{once:true}),0)}};
function inject(){if(document.getElementById('vc-room-style'))return;const s=document.createElement('style');s.id='vc-room-style';s.textContent=`.vc-room{height:100%;width:100%;display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box}.vc-center{width:100%;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;position:relative}.vc-name{font-size:20px;font-weight:800}.vc-status{font-size:12px;color:var(--muted)}.vc-members{width:min(900px,100%);display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:20px;justify-items:center}.vc-user{border:0;background:transparent;color:var(--text);padding:8px;border-radius:12px;display:flex;flex-direction:column;align-items:center;gap:7px;cursor:pointer}.vc-user:hover{background:var(--panel2)}.vc-avatar{width:68px;height:68px;border-radius:50%;overflow:hidden;background:var(--panel2);display:grid;place-items:center;font-size:22px;font-weight:800;outline:3px solid transparent}.vc-avatar img{width:100%;height:100%;object-fit:cover}.vc-user.speaking .vc-avatar{outline-color:var(--accent);box-shadow:0 0 0 5px color-mix(in srgb,var(--accent) 20%,transparent)}.vc-user.muted{opacity:.7}.vc-muted{font-size:12px}.vc-empty{color:var(--muted)}.vc-controls{display:flex;align-items:center;justify-content:center;gap:4px;padding:6px;background:var(--panel);border:1px solid var(--line);border-radius:14px}.vc-controls button{width:42px;height:42px;border:0;border-radius:10px;background:transparent;color:var(--text);font-size:18px;cursor:pointer;display:grid;place-items:center}.vc-controls button:hover{background:var(--panel2)}.vc-controls .leave{background:#c44;color:#fff}.vc-pop{position:absolute;bottom:72px;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px;min-width:230px;box-shadow:0 12px 35px #0007;display:flex;flex-direction:column;gap:10px;text-align:left}.vc-pop label,.vc-user-menu label{display:flex;flex-direction:column;gap:5px;color:var(--muted);font-size:12px}.vc-pop select{background:var(--input);color:var(--text);border:1px solid var(--line);padding:7px;border-radius:7px}.vc-user-menu{position:fixed;z-index:10001;background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:10px;display:flex;flex-direction:column;gap:9px;box-shadow:0 10px 30px #0007}.vc-user-menu button{border:0;background:var(--panel2);color:var(--text);padding:7px;border-radius:7px}@media(max-width:600px){.vc-room{padding:12px}.vc-members{grid-template-columns:repeat(2,minmax(100px,1fr));gap:10px}.vc-avatar{width:58px;height:58px}.vc-controls button{width:38px;height:38px}}`;document.head.appendChild(s)}
window.addEventListener('click',async e=>{const r=e.target.closest?.('#room-list [data-room]');if(r)await loadRoom(r.dataset.room);const b=e.target.closest?.('#p2p-channel-system [data-channel],#p2p-fixed-channel-sidebar [data-fc-channel]');if(!b||!roomCode)return;const id=b.dataset.channel||b.dataset.fcChannel,ch=channels[id];if(!channelIsVoice(ch))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{await join(roomCode,id,ch.name||id)}catch(err){console.error(err);alert(err.message||'Could not join voice channel.')}} ,true);
window.addEventListener('beforeunload',()=>{if(active&&me)remove(ref(db,`rooms/${active.room}/voice/${active.channel}/members/${me.uid}`))});onAuthStateChanged(auth,u=>{me=u;if(!u)leave()});inject();