import{getApps,getApp}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';import{getDatabase,ref,get,set,update,push,onValue,onDisconnect,remove}from'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
const app=getApps().length?getApp():null;if(!app)throw Error('Firebase is not initialized');const auth=getAuth(app),db=getDatabase(app);
let me=null,session=null,media=null,screen=null,muted=false,deafened=false,connections=new Map(),pendingIce=new Map(),listeners=[],raf=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};
const root=()=>session?`rooms/${session.room}/voice/${session.channel}`:'';
const inbox=()=>session?ref(db,`${root()}/signals/${me.uid}`):null;
function stopListeners(){listeners.splice(0).forEach(x=>x?.());}
function stopAnalysis(){if(raf)cancelAnimationFrame(raf);raf=0}
function localProfile(){return get(ref(db,`users/${me.uid}/profile`)).then(s=>s.val()||{})}
async function microphone(){if(media?.active)return media;if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Microphone access requires HTTPS.');media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(!media.getAudioTracks().length)throw Error('No microphone was found.');return media}
function audioElement(uid,stream){let a=document.querySelector(`audio[data-vc-audio="${CSS.escape(uid)}"]`);if(!a){a=document.createElement('audio');a.dataset.vcAudio=uid;a.autoplay=true;a.playsInline=true;document.body.append(a)}a.srcObject=stream;a.muted=deafened;a.play().catch(()=>{});return a}
function speaking(uid,stream){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=256;an.smoothingTimeConstant=.75;src.connect(an);const data=new Uint8Array(an.fftSize);let last=false;const loop=()=>{if(!session){ctx.close().catch(()=>{});return}an.getByteTimeDomainData(data);let sum=0;for(const n of data){const x=(n-128)/128;sum+=x*x}const active=Math.sqrt(sum/data.length)>.035;if(active!==last){last=active;setSpeaking(uid,active)}requestAnimationFrame(loop)};loop()}catch{}}
function setSpeaking(uid,value){const el=document.querySelector(`[data-vc-user="${CSS.escape(uid)}"]`);el?.classList.toggle('speaking',value)}
function renderMembers(members){const box=document.getElementById('vc-participants');if(!box)return;const entries=Object.values(members||{});box.innerHTML=entries.map(u=>`<button class="vc-participant${u.muted?' muted':''}" data-vc-user="${esc(u.uid)}" type="button"><span class="vc-avatar">${u.avatar?`<img src="${esc(u.avatar)}" alt="">`:esc((u.username||'U')[0].toUpperCase())}</span><span class="vc-name">${esc(u.username||'User')}</span>${u.muted?'<span class="vc-mute" aria-label="Muted">⌁</span>':''}</button>`).join('')||'<div class="vc-empty">Nobody is connected.</div>';box.querySelectorAll('[data-vc-user]').forEach(b=>b.onclick=()=>window.P2PVoiceChannel?.participantMenu?.(b.dataset.vcUser))}
async function send(to,type,data){if(!session)return;await push(ref(db,`${root()}/signals/${to}`),{from:me.uid,type,data,time:Date.now()})}
function queueCandidate(uid,c){const q=pendingIce.get(uid)||[];q.push(c);pendingIce.set(uid,q)}
async function flushCandidates(uid,pc){const q=pendingIce.get(uid)||[];pendingIce.delete(uid);for(const c of q)await pc.addIceCandidate(new RTCIceCandidate(c)).catch(()=>{})}
function closePeer(uid){const p=connections.get(uid);p?.pc?.close();connections.delete(uid);pendingIce.delete(uid);document.querySelector(`audio[data-vc-audio="${CSS.escape(uid)}"]`)?.remove();}
async function makePeer(uid,initiator){if(!session||uid===me.uid)return null;let item=connections.get(uid);if(item)return item.pc;await microphone();const pc=new RTCPeerConnection(pcConfig);const item2={pc,remoteDescription:false};connections.set(uid,item2);media.getTracks().forEach(t=>pc.addTrack(t,media));if(screen?.getVideoTracks()[0])pc.addTrack(screen.getVideoTracks()[0],screen);pc.ontrack=e=>{const s=e.streams?.[0]||new MediaStream([e.track]);if(e.track.kind==='video'){const v=document.getElementById('vc-screen');if(v){v.srcObject=s;v.hidden=false}}else{audioElement(uid,s);speaking(uid,s)}};pc.onicecandidate=e=>{if(e.candidate)send(uid,'candidate',e.candidate.toJSON())};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))closePeer(uid);if(pc.connectionState==='connected')setStatus('Connected')};if(initiator){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await send(uid,'offer',{type:offer.type,sdp:offer.sdp})}return pc}
async function handleSignal(v){if(!session||v.to===me.uid||v.from===me.uid)return;const uid=v.from;if(v.type==='offer'){const pc=await makePeer(uid,false),item=connections.get(uid);await pc.setRemoteDescription(new RTCSessionDescription(v.data));item.remoteDescription=true;await flushCandidates(uid,pc);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await send(uid,'answer',{type:answer.type,sdp:answer.sdp})}else if(v.type==='answer'){const item=connections.get(uid);if(item&&!item.remoteDescription){await item.pc.setRemoteDescription(new RTCSessionDescription(v.data));item.remoteDescription=true;await flushCandidates(uid,item.pc)}}else if(v.type==='candidate'){const item=connections.get(uid);if(!item||!item.remoteDescription)queueCandidate(uid,v.data);else await item.pc.addIceCandidate(new RTCIceCandidate(v.data)).catch(()=>{})}}
async function syncMembers(members){renderMembers(members);for(const uid of Object.keys(members||{})){if(uid===me.uid)continue;if(!connections.has(uid)&&me.uid<uid)await makePeer(uid,true)}for(const uid of [...connections.keys()])if(!members[uid])closePeer(uid)}
function setStatus(s){document.getElementById('vc-status')&&(document.getElementById('vc-status').textContent=s)}
function ui(){const c=document.getElementById('content');if(!c)return;c.innerHTML=`<section class="vc-room"><div class="vc-room-inner"><div class="vc-title">🔊 ${esc(session.name)}</div><div id="vc-status" class="vc-status">Connecting…</div><video id="vc-screen" class="vc-screen" autoplay playsinline hidden></video><div id="vc-participants" class="vc-participants"></div><div class="vc-controls" role="toolbar" aria-label="Voice controls"><button id="vc-mic" title="Mute" aria-label="Mute" type="button">🎤</button><button id="vc-mic-more" class="vc-split" title="Microphone settings" aria-label="Microphone settings" type="button">⌄</button><button id="vc-deafen" title="Deafen" aria-label="Deafen" type="button">🔊</button><button id="vc-screen-btn" title="Share screen" aria-label="Share screen" type="button">🖥️</button><button id="vc-leave" class="vc-leave" title="Leave voice channel" aria-label="Leave voice channel" type="button">☎</button></div><div id="vc-popover" class="vc-popover" hidden></div></div></section>`;document.getElementById('vc-mic').onclick=toggleMute;document.getElementById('vc-deafen').onclick=toggleDeafen;document.getElementById('vc-mic-more').onclick=microphonePopover;document.getElementById('vc-screen-btn').onclick=toggleScreen;document.getElementById('vc-leave').onclick=leave}
async function toggleMute(){muted=!muted;media?.getAudioTracks().forEach(t=>t.enabled=!muted);await update(ref(db,`${root()}/members/${me.uid}`),{muted});const b=document.getElementById('vc-mic');if(b){b.textContent=muted?'🎙️':'🎤';b.title=muted?'Unmute':'Mute';b.setAttribute('aria-label',b.title)}}
async function toggleDeafen(){deafened=!deafened;document.querySelectorAll('audio[data-vc-audio]').forEach(a=>a.muted=deafened);await update(ref(db,`${root()}/members/${me.uid}`),{deafened});const b=document.getElementById('vc-deafen');if(b){b.textContent=deafened?'🔇':'🔊';b.title=deafened?'Undeafen':'Deafen';b.setAttribute('aria-label',b.title)}}
async function microphonePopover(){const p=document.getElementById('vc-popover');if(!p)return;if(!p.hidden){p.hidden=true;return}let devices=[];try{devices=await navigator.mediaDevices.enumerateDevices()}catch{}const inputs=devices.filter(d=>d.kind==='audioinput');p.innerHTML=`<b>Microphone</b><label>Input<select id="vc-input-device">${inputs.map(d=>`<option value="${esc(d.deviceId)}">${esc(d.label||'Microphone')}</option>`).join('')}</select></label><label>Input volume<input id="vc-input-volume" type="range" min="0" max="100" value="100"></label>`;p.hidden=false;document.getElementById('vc-input-volume').oninput=e=>media?.getAudioTracks().forEach(t=>t.enabled=Number(e.target.value)>0);document.getElementById('vc-input-device').onchange=async e=>{try{const old=media;media=await navigator.mediaDevices.getUserMedia({audio:{deviceId:{exact:e.target.value},echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const track=media.getAudioTracks()[0];connections.forEach(({pc})=>pc.getSenders().find(s=>s.track?.kind==='audio')?.replaceTrack(track));old?.getTracks().forEach(t=>t.stop())}catch(err){alert(err.message||'Could not change microphone.')}}}
async function toggleScreen(){if(!navigator.mediaDevices?.getDisplayMedia){alert('Screen sharing is not supported by this browser.');return}if(screen){screen.getTracks().forEach(t=>t.stop());screen=null;document.getElementById('vc-screen').hidden=true;for(const{pc}of connections.values()){const s=pc.getSenders().find(x=>x.track?.kind==='video');if(s)s.replaceTrack(null)}return}try{screen=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const vt=screen.getVideoTracks()[0];for(const{pc}of connections.values()){const s=pc.getSenders().find(x=>x.track?.kind==='video');if(s)await s.replaceTrack(vt);else pc.addTrack(vt,screen)}const v=document.getElementById('vc-screen');v.srcObject=screen;v.hidden=false;vt.onended=()=>toggleScreen()}catch(e){if(e?.name!=='AbortError')alert(e.message||'Could not start screen sharing.')}}
async function join(room,channel,name){if(!me)throw Error('You must be signed in.');if(session?.room===room&&session?.channel===channel)return;await leave();session={room,channel,name};ui();await microphone();const p=await localProfile();const member=ref(db,`${root()}/members/${me.uid}`);await onDisconnect(member).remove();await set(member,{uid:me.uid,username:p.username||me.displayName||'User',avatar:p.avatarData||p.avatar||null,muted:false,deafened:false,joinedAt:Date.now()});const membersRef=ref(db,`${root()}/members`);listeners.push(onValue(membersRef,s=>syncMembers(s.val()||{})));listeners.push(onValue(inbox(),s=>{Object.values(s.val()||{}).forEach(handleSignal)}));setStatus('Connected');return true}
async function leave(){if(!session)return;const old=session;session=null;stopListeners();stopAnalysis();for(const uid of [...connections.keys()])closePeer(uid);screen?.getTracks().forEach(t=>t.stop());screen=null;media?.getTracks().forEach(t=>t.stop());media=null;document.querySelectorAll('audio[data-vc-audio]').forEach(a=>a.remove());document.getElementById('content')?.querySelector('.vc-room')?.remove();await remove(ref(db,`rooms/${old.room}/voice/${old.channel}/members/${me?.uid}`)).catch(()=>{})}
function participantMenu(uid){const m=document.createElement('div');m.className='vc-user-menu';m.innerHTML=`<b>${esc(uid===me.uid?'You':'Participant')}</b><button type="button" id="vc-local-mute">Local mute</button><label>Volume<input type="range" min="0" max="200" value="100"></label>`;document.body.append(m);const a=document.querySelector(`audio[data-vc-audio="${CSS.escape(uid)}"]`);m.querySelector('input').oninput=e=>{if(a)a.volume=Number(e.target.value)/100};m.querySelector('#vc-local-mute').onclick=()=>{if(a)a.muted=!a.muted};setTimeout(()=>document.addEventListener('click',()=>m.remove(),{once:true}),0)}
function injectStyle(){if(document.getElementById('vc-rebuild-style'))return;const s=document.createElement('style');s.id='vc-rebuild-style';s.textContent=`.vc-room{height:100%;min-height:0;display:flex;align-items:center;justify-content:center;box-sizing:border-box;padding:28px}.vc-room-inner{width:100%;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;position:relative;box-sizing:border-box}.vc-title{font-size:20px;font-weight:800}.vc-status{font-size:12px;color:var(--muted)}.vc-participants{width:min(900px,100%);display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:22px;justify-items:center;align-items:center}.vc-participant{border:0;background:transparent;color:var(--text);display:flex;flex-direction:column;align-items:center;gap:8px;cursor:pointer;padding:8px;border-radius:12px}.vc-participant:hover{background:var(--panel2)}.vc-avatar{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;overflow:hidden;background:var(--panel2);font-weight:800;font-size:24px;outline:3px solid transparent}.vc-avatar img{width:100%;height:100%;object-fit:cover}.vc-participant.speaking .vc-avatar{outline-color:var(--accent);box-shadow:0 0 0 5px color-mix(in srgb,var(--accent) 20%,transparent)}.vc-participant.muted .vc-name{opacity:.65}.vc-mute{font-size:13px;color:var(--muted)}.vc-empty{color:var(--muted);text-align:center}.vc-screen{width:min(900px,90%);max-height:55%;object-fit:contain;border-radius:12px;background:#000}.vc-controls{display:flex;align-items:center;justify-content:center;gap:5px;padding:6px;border-radius:14px;background:var(--panel);border:1px solid var(--line)}.vc-controls button{width:42px;height:42px;border:0;background:transparent;color:var(--text);border-radius:10px;font-size:18px;cursor:pointer;display:grid;place-items:center}.vc-controls button:hover{background:var(--panel2)}.vc-controls .vc-split{width:22px;margin-left:-5px;font-size:13px}.vc-controls .vc-leave{color:#fff;background:#c44}.vc-popover,.vc-user-menu{position:absolute;bottom:70px;background:var(--panel);border:1px solid var(--line);box-shadow:0 12px 35px #0007;border-radius:12px;padding:12px;min-width:220px;display:flex;flex-direction:column;gap:10px;text-align:left}.vc-popover label,.vc-user-menu label{display:flex;flex-direction:column;gap:5px;color:var(--muted);font-size:12px}.vc-popover select{background:var(--input);color:var(--text);border:1px solid var(--line);border-radius:7px;padding:7px}.vc-user-menu{position:fixed;bottom:auto;z-index:10001}.vc-user-menu button{border:0;background:var(--panel2);color:var(--text);padding:8px;border-radius:7px;text-align:left}@media(max-width:600px){.vc-room{padding:16px}.vc-avatar{width:60px;height:60px}.vc-participants{grid-template-columns:repeat(2,minmax(100px,1fr));gap:12px}.vc-controls button{width:38px;height:38px}}`;document.head.appendChild(s)}
window.P2PVoiceChannel={join,leave,participantMenu};injectStyle();onAuthStateChanged(auth,u=>{me=u;if(!u)leave()});window.addEventListener('beforeunload',()=>{if(session&&me)remove(ref(db,`${root()}/members/${me.uid}`))});