import {getDatabase,ref,set,get,remove} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
import {getAuth} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
const db=getDatabase(),auth=getAuth();
const EMOJI=['😀','😃','😄','😁','😆','😅','😂','🤣','😊','🙂','🙃','😉','😍','🥰','😘','😎','🤔','😐','🙄','😏','😮','😴','😕','😟','🙁','😲','😳','🥺','😭','😤','😠','😡','🤬','🤯','😱','😨','😰','😢','🤗','🤩','🥳','😇','👍','👎','👏','🙌','🙏','❤️','🧡','💛','💚','💙','💜','🖤','🤍','🔥','⭐','🎉','💯','💀','👀','✨','🤝','💪','👌','✌️','🚀','🎮','🍕','💻'];
let current=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function picker(anchor,onPick){document.getElementById('p2p-emoji-picker')?.remove();const p=document.createElement('div');p.id='p2p-emoji-picker';p.className='p2p-emoji-picker';p.innerHTML=EMOJI.map(e=>`<button type="button" data-e="${esc(e)}">${e}</button>`).join('');document.body.appendChild(p);const r=anchor.getBoundingClientRect();p.style.left=Math.min(Math.max(8,r.left),innerWidth-p.offsetWidth-8)+'px';p.style.top=Math.max(8,r.top-p.offsetHeight-8)+'px';p.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{onPick(b.dataset.e);p.remove()});setTimeout(()=>document.addEventListener('click',e=>{if(!p.contains(e.target)&&e.target!==anchor)p.remove()},{once:true}),0)}
async function react(id,emoji){const uid=auth.currentUser?.uid;if(!uid||!current)return;const safe=emoji.replace(/[.#$\[\]/g,'');const path=`${current.type==='dm'?'dms/'+current.key:'rooms/'+current.key}/messages/${id}/reactions/${safe}`;const snap=await get(ref(db,path));const users=snap.val()||{};if(users[uid])await remove(ref(db,`${path}/${uid}`));else await set(ref(db,`${path}/${uid}`),true)}
function inferFromClick(el){const room=el.closest('[data-room]')?.dataset.room;const dm=el.closest('[data-dm]')?.dataset.dm;if(room)current={type:'room',key:room};else if(dm){const me=auth.currentUser?.uid;if(me)current={type:'dm',key:[me,dm].sort().join('_')}}}
document.addEventListener('click',e=>{inferFromClick(e.target);const reactBtn=e.target.closest('[data-action="react"]');if(reactBtn){e.preventDefault();e.stopImmediatePropagation();picker(reactBtn,emoji=>react(reactBtn.dataset.id,emoji));return}const pill=e.target.closest('.reactions span');if(pill){const id=pill.closest('.message')?.dataset.messageId;if(id){const raw=pill.textContent.trim(),emoji=raw.replace(/\s+\d+$/,'');react(id,emoji)}return}const composer=e.target.closest('#composer-emoji');if(composer){picker(composer,emoji=>{const msg=document.getElementById('msg');if(msg){msg.value+=emoji;msg.focus()}})}},true);
const style=document.createElement('style');style.textContent=`.p2p-emoji-picker{position:fixed;z-index:99999;width:360px;max-height:300px;overflow:auto;display:grid;grid-template-columns:repeat(8,1fr);gap:3px;padding:10px;background:var(--panel,#171a22);border:1px solid var(--line,#292e3a);border-radius:12px;box-shadow:0 10px 30px #0008}.p2p-emoji-picker button{border:0;background:transparent;border-radius:7px;font-size:24px;width:38px;height:38px;padding:0}.p2p-emoji-picker button:hover{background:var(--panel2,#20242e)}.reactions span{font-size:15px!important;padding:4px 9px!important;cursor:pointer;user-select:none}.reactions span:hover{background:var(--accent,#5865f2);color:#fff}`;document.head.appendChild(style);