import {getAuth} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import {getDatabase,ref,get,set,update} from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js';
const auth=getAuth(),db=getDatabase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function modal(html){const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;return root.firstElementChild}
async function inviteRoom(code){const uid=auth.currentUser?.uid;if(!uid)return;const snap=await get(ref(db,`rooms/${code}/meta`));const room=snap.val()||{};if(room.owner!==uid){alert('Only the room leader can create an invite code.');return}let invite=room.inviteCode;if(!invite){invite=makeCode();await update(ref(db,`rooms/${code}/meta`),{inviteCode:invite})}const m=modal(`<button class="x" id="invite-x">×</button><h2>Invite people</h2><p class="muted">Share this code with your friends. They can enter it in the Room code box and press Join.</p><div class="invite-code">${esc(invite)}</div><div class="modal-actions"><button id="invite-copy">Copy code</button><button id="invite-new">Make new code</button><button id="invite-close">Close</button></div>`);const close=()=>m.remove();document.getElementById('invite-x').onclick=close;document.getElementById('invite-close').onclick=close;document.getElementById('invite-copy').onclick=async()=>{try{await navigator.clipboard.writeText(invite);document.getElementById('invite-copy').textContent='Copied!'}catch{prompt('Copy this invite code:',invite)}};document.getElementById('invite-new').onclick=async()=>{invite=makeCode();await update(ref(db,`rooms/${code}/meta`),{inviteCode:invite});m.querySelector('.invite-code').textContent=invite;document.getElementById('invite-copy').textContent='Copy code'} }
function addInviteButton(){const actions=document.getElementById('header-actions');if(!actions)return;const title=document.getElementById('view-title')?.textContent;const sub=document.getElementById('view-sub')?.textContent;if(sub!=='Room')return;const code=window.P2PActiveRoom;if(!code||actions.querySelector('#room-invite'))return;const b=document.createElement('button');b.id='room-invite';b.className='header-action';b.textContent='Invite';b.title='Create an invite code';b.onclick=()=>inviteRoom(code);actions.prepend(b)}
new MutationObserver(addInviteButton).observe(document.getElementById('header-actions'),{childList:true,subtree:true});
window.addEventListener('p2p-room-open',e=>{window.P2PActiveRoom=e.detail?.code;addInviteButton()});
