import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import { getDatabase, ref, set, push, onValue, get, update, remove } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js";

const firebaseConfig = { apiKey:"AIzaSyAucXMpqBhYbZy1fSbkTKHX23y9bpx1hec", authDomain:"p2pminimalchat.firebaseapp.com", databaseURL:"https://p2pminimalchat-default-rtdb.firebaseio.com", projectId:"p2pminimalchat", storageBucket:"p2pminimalchat.firebasestorage.app", messagingSenderId:"37869407438", appId:"1:37869407438:web:63485dde33bb8710f8d49f", measurementId:"G-9JNKBE87C3" };
const app=initializeApp(firebaseConfig,"social"); const auth=getAuth(app); const db=getDatabase(app);
let uid=null, me=null, friends={}, activeChat=null, users={};
const fallback="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23949ba4'><circle cx='12' cy='12' r='10'/></svg>";
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const avatar=u=>u?.avatarData||fallback;
const panel=()=>document.getElementById("social-view");
function showSocial(){ document.getElementById("welcome-view")?.classList.add("hidden"); document.getElementById("room-view")?.classList.add("hidden"); document.getElementById("profile-card")?.classList.add("hidden"); document.getElementById("room-settings-card")?.classList.add("hidden"); panel()?.classList.remove("hidden"); }
function showAlert(t){const a=document.getElementById("alert-banner"); if(a){a.textContent=t;a.classList.remove("hidden");setTimeout(()=>a.classList.add("hidden"),3500)}}
function cid(a,b){return [a,b].sort().join("_")}
function navButton(label,id){const b=document.createElement("button");b.className="social-nav-btn";b.id=id;b.textContent=label;return b}
function makeUI(){
 const side=document.querySelector(".discord-sidebar"), rooms=document.getElementById("room-menu-list"), actions=document.querySelector(".sidebar-actions");
 if(!side||document.getElementById("social-sidebar")) return;
 const box=document.createElement("div"); box.id="social-sidebar"; box.innerHTML=`<div class="social-heading">P2P SOCIAL</div><div id="social-nav"></div><div class="social-section-title">FRIENDS</div><div id="friend-list"></div><div class="social-section-title">GROUPS</div><div id="group-list"></div>`;
 side.insertBefore(box,rooms);
 actions.innerHTML=`<input id="sidebar-room-code" type="text" placeholder="Join Code" maxlength="6"><div class="action-buttons"><button id="join-room-btn" class="btn-small">Join Room</button><button id="create-room-btn" class="btn-small btn-primary">Create Room</button></div>`;
 const main=document.querySelector(".discord-main"); const v=document.createElement("section"); v.id="social-view"; v.className="social-view hidden"; main.appendChild(v);
 document.getElementById("social-nav").append(navButton("Find People","social-search-btn"),navButton("Friend Requests","social-requests-btn"),navButton("Create Group","social-create-group-btn"));
 document.getElementById("social-search-btn").onclick=searchView; document.getElementById("social-requests-btn").onclick=requestView; document.getElementById("social-create-group-btn").onclick=createGroupView;
 const code=document.getElementById("sidebar-room-code"); document.getElementById("create-room-btn").onclick=async()=>{if(!uid)return;const code=Math.random().toString(36).substring(2,8).toUpperCase();await set(ref(db,`rooms/${code}/meta`),{roomName:`Room-${code}`,roomIcon:""});await set(ref(db,`users/${uid}/joinedRooms/${code}`),true);location.reload()};
 document.getElementById("join-room-btn").onclick=async()=>{const c=code.value.trim().toUpperCase();if(!c)return showAlert("Enter a room code.");const s=await get(ref(db,`rooms/${c}/meta`));if(!s.exists())return showAlert("Room not found.");await set(ref(db,`users/${uid}/joinedRooms/${c}`),true);location.reload()};
 addStyle();
}
function addStyle(){if(document.getElementById("social-style"))return;const s=document.createElement("style");s.id="social-style";s.textContent=`#social-sidebar{border-bottom:1px solid var(--border);padding:10px 8px;max-height:45%;overflow:auto}.social-heading,.social-section-title{font-size:.7rem;font-weight:700;color:var(--text-muted);letter-spacing:.06em;padding:4px 8px}.social-section-title{margin-top:10px}.social-nav-btn{display:block;width:100%;border:0;background:transparent;color:var(--text-muted);text-align:left;padding:7px 10px;border-radius:5px;cursor:pointer}.social-nav-btn:hover{background:var(--border);color:var(--text)}.social-person{display:flex;align-items:center;gap:8px;padding:7px 8px;border-radius:5px;cursor:pointer}.social-person:hover{background:var(--border)}.social-person img{width:30px;height:30px;border-radius:50%;object-fit:cover}.social-person span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.social-view{height:100%;display:flex;flex-direction:column;background:var(--bg-main)}.social-top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border);padding:12px 4px}.social-title{font-size:1.15rem;font-weight:700}.social-body{flex:1;overflow:auto;padding:18px 8px}.social-card{max-width:720px;margin:0 auto;background:var(--bg-sidebar);border:1px solid var(--border);border-radius:8px;padding:16px}.social-card h2{margin-bottom:12px}.social-input{width:100%;padding:10px;border:1px solid var(--border);background:var(--bg-inputs);color:var(--text);border-radius:5px;margin-bottom:10px}.social-result{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;border-bottom:1px solid var(--border)}.social-user{display:flex;align-items:center;gap:10px;min-width:0}.social-user img{width:42px;height:42px;border-radius:50%;object-fit:cover}.social-user small{display:block;color:var(--text-muted)}.social-actions{display:flex;gap:6px;flex-wrap:wrap}.social-messages{height:calc(100vh - 180px);overflow:auto;padding:12px}.social-msg{margin:7px 0;max-width:75%}.social-msg.mine{margin-left:auto;text-align:right}.social-bubble{display:inline-block;padding:8px 11px;background:var(--bg-sidebar);border:1px solid var(--border);border-radius:9px;text-align:left}.social-composer{display:flex;gap:8px;border-top:1px solid var(--border);padding:10px}.social-composer input{flex:1}.social-member{display:flex;align-items:center;gap:8px;padding:7px}.social-member input{width:18px;height:18px}`;document.head.appendChild(s)}
async function publicProfile(id){const s=await get(ref(db,`userDirectory/${id}`));return s.val()||null}
function directorySync(){if(!uid)return;onValue(ref(db,`users/${uid}/profile`),async s=>{const p=s.val()||{};me={uid,username:p.username||auth.currentUser?.displayName||"User",avatarData:p.avatarData||fallback,statusText:p.statusText||""};await set(ref(db,`userDirectory/${uid}`),{uid,username:me.username,avatarData:me.avatarData,statusText:me.statusText})})}
function loadFriends(){onValue(ref(db,`friends/${uid}`),s=>{friends=s.val()||{};renderFriends()});onValue(ref(db,`groupInvites/${uid}`),()=>requestView())}
function renderFriends(){const el=document.getElementById("friend-list");if(!el)return;el.innerHTML="";Object.entries(friends).forEach(([id,f])=>{const d=document.createElement("div");d.className="social-person";d.innerHTML=`<img src="${avatar(f)}"><span>${esc(f.username||id)}</span>`;d.onclick=()=>openDM(id,f.username||"Friend");el.appendChild(d)})}
function searchView(){showSocial();const v=panel();v.innerHTML=`<div class="social-top"><div class="social-title">Find People</div></div><div class="social-body"><div class="social-card"><input class="social-input" id="user-search" placeholder="Search by username..."><div id="search-results"></div></div></div>`;const i=document.getElementById("user-search");i.oninput=async()=>{const q=i.value.trim().toLowerCase();const r=document.getElementById("search-results");r.innerHTML="";if(q.length<2)return;const s=await get(ref(db,"userDirectory"));const all=s.val()||{};Object.entries(all).filter(([id,u])=>id!==uid&&(u.username||"").toLowerCase().includes(q)).slice(0,20).forEach(([id,u])=>{const row=document.createElement("div");row.className="social-result";row.innerHTML=`<div class="social-user"><img src="${avatar(u)}"><div><b>${esc(u.username)}</b><small>${esc(u.statusText||"")}</small></div></div><button class="btn-small btn-primary">Add Friend</button>`;row.querySelector("button").onclick=()=>sendFriend(id,u);r.appendChild(row)})}}
async function sendFriend(id,u){if(friends[id])return showAlert("Already friends.");await set(ref(db,`friendRequests/${id}/${uid}`),{uid,username:me.username,avatarData:me.avatarData,statusText:me.statusText,timestamp:Date.now()});showAlert(`Friend request sent to ${u.username}.`)}
async function requestView(){showSocial();const v=panel();v.innerHTML=`<div class="social-top"><div class="social-title">Friend Requests</div></div><div class="social-body"><div class="social-card"><div id="requests"></div><h3 style="margin-top:18px">Group Invites</h3><div id="invites"></div></div></div>`;const r=await get(ref(db,`friendRequests/${uid}`));const requests=r.val()||{};const re=document.getElementById("requests");if(!Object.keys(requests).length)re.innerHTML='<p style="color:var(--text-muted)">No pending friend requests.</p>';for(const [id,x] of Object.entries(requests)){const row=document.createElement("div");row.className="social-result";row.innerHTML=`<div class="social-user"><img src="${avatar(x)}"><b>${esc(x.username)}</b></div><div class="social-actions"><button class="btn-small btn-primary">Accept</button><button class="btn-small">Decline</button></div>`;const bs=row.querySelectorAll("button");bs[0].onclick=()=>acceptFriend(id,x);bs[1].onclick=()=>remove(ref(db,`friendRequests/${uid}/${id}`));re.appendChild(row)}const gi=await get(ref(db,`groupInvites/${uid}`));const inv=gi.val()||{};const ie=document.getElementById("invites");if(!Object.keys(inv).length)ie.innerHTML='<p style="color:var(--text-muted)">No group invites.</p>';Object.entries(inv).forEach(([gid,x])=>{const row=document.createElement("div");row.className="social-result";row.innerHTML=`<div><b>${esc(x.name)}</b><small>Invited by ${esc(x.inviterName||"friend")}</small></div><button class="btn-small btn-primary">Join</button>`;row.querySelector("button").onclick=()=>acceptGroup(gid,x);ie.appendChild(row)})}
async function acceptFriend(id,x){const p={uid:id,username:x.username,avatarData:x.avatarData||fallback,statusText:x.statusText||""};await update(ref(db),{[`friends/${uid}/${id}`]:p,[`friends/${id}/${uid}`]:{...p,uid},[`friendRequests/${uid}/${id}`]:null});showAlert("Friend added.");requestView()}
function createGroupView(){showSocial();const v=panel();v.innerHTML=`<div class="social-top"><div class="social-title">Create Group</div></div><div class="social-body"><div class="social-card"><input class="social-input" id="group-name" placeholder="Group name"><div id="group-friends"></div><button id="make-group" class="btn-primary" style="margin-top:12px">Create Group</button></div></div>`;const f=document.getElementById("group-friends");Object.entries(friends).forEach(([id,x])=>{const row=document.createElement("label");row.className="social-member";row.innerHTML=`<input type="checkbox" value="${id}"><img src="${avatar(x)}" style="width:30px;height:30px;border-radius:50%"><span>${esc(x.username)}</span>`;f.appendChild(row)});document.getElementById("make-group").onclick=createGroup}
async function createGroup(){const name=document.getElementById("group-name").value.trim();if(!name)return showAlert("Give the group a name.");const ids=[...document.querySelectorAll("#group-friends input:checked")].map(x=>x.value);const gid=push(ref(db,"groups")).key;const members={[uid]:true};ids.forEach(x=>members[x]=true);await set(ref(db,`groups/${gid}`),{meta:{name,owner:uid,createdAt:Date.now()},members});for(const id of ids)await set(ref(db,`groupInvites/${id}/${gid}`),{name,inviterName:me.username,groupId:gid});openGroup(gid,name)}
async function acceptGroup(gid,x){await update(ref(db),{[`groups/${gid}/members/${uid}`]:true,[`groupInvites/${uid}/${gid}`]:null});openGroup(gid,x.name)}
function openGroup(gid,name){showSocial();activeChat={type:"group",id:gid,name};renderChat();listenGroup(gid)}
async function openDM(id,name){const c=cid(uid,id);await update(ref(db),{[`dms/${c}/meta`]:{a:uid,b:id},[`users/${uid}/dms/${c}`]:true,[`users/${id}/dms/${c}`]:true});showSocial();activeChat={type:"dm",id:c,name};renderChat();listenDM(c)}
function renderChat(){const v=panel();v.innerHTML=`<div class="social-top"><div class="social-title">${esc(activeChat.name)}</div><div class="social-actions">${activeChat.type==="group"?'<button class="btn-small" id="invite-group">Invite Friends</button>':''}<button class="btn-small" id="back-social">Back</button></div></div><div class="social-messages" id="social-messages"></div><div class="social-composer"><input class="social-input" id="social-message" placeholder="Message ${activeChat.type==="group"?"group":"friend"}..."><button class="btn-primary" id="social-send">Send</button></div>`;document.getElementById("back-social").onclick=searchView;if(activeChat.type==="group")document.getElementById("invite-group").onclick=()=>inviteView(activeChat.id,activeChat.name);document.getElementById("social-send").onclick=sendMessage;document.getElementById("social-message").onkeydown=e=>{if(e.key==="Enter")sendMessage()}}
function listenDM(c){onValue(ref(db,`dms/${c}/messages`),s=>renderMessages(s.val()||{}))}
function listenGroup(g){onValue(ref(db,`groups/${g}/messages`),s=>renderMessages(s.val()||{}))}
function renderMessages(data){const box=document.getElementById("social-messages");if(!box)return;box.innerHTML="";Object.values(data).sort((a,b)=>(a.timestamp||0)-(b.timestamp||0)).forEach(m=>{const d=document.createElement("div");d.className=`social-msg ${m.senderUid===uid?"mine":""}`;d.innerHTML=`<div class="social-bubble"><b>${esc(m.sender)}</b><br>${esc(m.text)}</div>`;box.appendChild(d)});box.scrollTop=box.scrollHeight}
async function sendMessage(){const i=document.getElementById("social-message"),text=i.value.trim();if(!text||!activeChat)return;const p=activeChat.type==="group`?`groups/${activeChat.id}/messages`:`dms/${activeChat.id}/messages`;await push(ref(db,p),{senderUid:uid,sender:me.username,text,timestamp:Date.now()});i.value=""}
function inviteView(gid,name){showSocial();const v=panel();v.innerHTML=`<div class="social-top"><div class="social-title">Invite Friends to ${esc(name)}</div></div><div class="social-body"><div class="social-card" id="invite-list"></div></div>`;const box=document.getElementById("invite-list");Object.entries(friends).forEach(([id,x])=>{const row=document.createElement("div");row.className="social-result";row.innerHTML=`<div class="social-user"><img src="${avatar(x)}"><b>${esc(x.username)}</b></div><button class="btn-small btn-primary">Invite</button>`;row.querySelector("button").onclick=async()=>{await set(ref(db,`groupInvites/${id}/${gid}`),{name,inviterName:me.username,groupId:gid});showAlert(`Invited ${x.username}.`)};box.appendChild(row)})}
makeUI();
// Intercept the old room controls by replacing them before app.js registers its listeners.
for(const id of ["join-room-btn","create-room-btn"]){const old=document.getElementById(id);if(old){const fresh=old.cloneNode(true);old.replaceWith(fresh)}}
// Re-bind the passwordless room controls after cloning.
setTimeout(()=>{const code=document.getElementById("sidebar-room-code");document.getElementById("create-room-btn")?.addEventListener("click",async()=>{const c=Math.random().toString(36).substring(2,8).toUpperCase();await set(ref(db,`rooms/${uid}/meta`),{roomName:`Room-${c}`,roomIcon:""});});},0);
onAuthStateChanged(auth,user=>{uid=user?.uid||null;if(uid){makeUI();directorySync();loadFriends();onValue(ref(db,`groupMemberships/${uid}`),()=>{});onValue(ref(db,`users/${uid}/groups`),()=>{})}});